// Code generated by tools/codegen; DO NOT EDIT.
// Source: src/StatisticsAnalysisTool/Network/EventCodes.cs (ref: main)
// Upstream: Triky313/AlbionOnline-StatisticsAnalysis (GPL-3.0)

package protocol

// EventCode identifies a Photon event. Values mirror the upstream positional enum.
type EventCode int

const (
	EventCodeUnused EventCode = 0
	EventCodeLeave EventCode = 1
	EventCodeJoinFinished EventCode = 2 // <- UserInfo,
	EventCodeMove EventCode = 3
	EventCodeTeleport EventCode = 4
	EventCodeChangeEquipment EventCode = 5
	EventCodeHealthUpdate EventCode = 6
	EventCodeHealthUpdates EventCode = 7
	EventCodeEnergyUpdate EventCode = 8
	EventCodeDamageShieldUpdate EventCode = 9
	EventCodeCraftingFocusUpdate EventCode = 10
	EventCodeActiveSpellEffectsUpdate EventCode = 11
	EventCodeResetCooldowns EventCode = 12
	EventCodeAttack EventCode = 13
	EventCodeCastStart EventCode = 14
	EventCodeChannelingUpdate EventCode = 15
	EventCodeCastCancel EventCode = 16
	EventCodeCastTimeUpdate EventCode = 17
	EventCodeCastFinished EventCode = 18
	EventCodeCastSpell EventCode = 19
	EventCodeCastSpells EventCode = 20
	EventCodeCastHit EventCode = 21
	EventCodeCastHits EventCode = 22
	EventCodeStoredTargetsUpdate EventCode = 23
	EventCodeChannelingEnded EventCode = 24
	EventCodeAttackBuilding EventCode = 25
	EventCodeInventoryPutItem EventCode = 26 // map[0:652 1:6 2:[118 -97 114 112 -46 84 -60 75 -103 -93 -3 -29 118 -125 -50 96] 3:17 252:23] (0: ObjectId, 1: Inventory slot (no value is slot 0), 2: Interac...
	EventCodeInventoryDeleteItem EventCode = 27 // map[0:754 1:48 252:24] (0: ObjectId)
	EventCodeInventoryState EventCode = 28
	EventCodeNewCharacter EventCode = 29
	EventCodeNewEquipmentItem EventCode = 30 // map[0:657 1:2036 2:1 4:28169331 5:Apolo540 6:3 7:90000000 8:[] 9:[0] 252:27] (0: ObjectId, 1: ItemId, 2: Amount, 4: Est. market value, 5: CrafterName)
	EventCodeNewSiegeBannerItem EventCode = 31
	EventCodeNewSimpleItem EventCode = 32 // map[0:505 1:7006 2:1 3:true 4:29033970 252:27] (0: ObjectId, 1: ItemId, 2: Amount, 4: Est. market value)
	EventCodeNewFurnitureItem EventCode = 33
	EventCodeNewKillTrophyItem EventCode = 34
	EventCodeNewJournalItem EventCode = 35
	EventCodeNewLaborerItem EventCode = 36 // [0:513 1:7996 2:4 4:522947156 5: 6:10000 7:72000000 252:32]
	EventCodeNewEquipmentItemLegendarySoul EventCode = 37
	EventCodeNewSimpleHarvestableObject EventCode = 38
	EventCodeNewSimpleHarvestableObjectList EventCode = 39
	EventCodeNewHarvestableObject EventCode = 40 // map[0:[3405 3468] 1:[6 6] 2:[3 2] 3:[182 -383 176 -369 183 -371] 4:[3 3] 252:35] - 0: ObjectId 2: Max charges, 4: Current charges
	EventCodeNewTreasureDestinationObject EventCode = 41
	EventCodeTreasureDestinationObjectStatus EventCode = 42
	EventCodeCloseTreasureDestinationObject EventCode = 43
	EventCodeNewSilverObject EventCode = 44
	EventCodeNewBuilding EventCode = 45
	EventCodeHarvestableChangeState EventCode = 46
	EventCodeMobChangeState EventCode = 47
	EventCodeFactionBuildingInfo EventCode = 48
	EventCodeCraftBuildingInfo EventCode = 49
	EventCodeRepairBuildingInfo EventCode = 50
	EventCodeMeldBuildingInfo EventCode = 51
	EventCodeConstructionSiteInfo EventCode = 52
	EventCodePlayerBuildingInfo EventCode = 53
	EventCodeFarmBuildingInfo EventCode = 54
	EventCodeTutorialBuildingInfo EventCode = 55
	EventCodeLaborerObjectInfo EventCode = 56
	EventCodeLaborerObjectJobInfo EventCode = 57
	EventCodeMarketPlaceBuildingInfo EventCode = 58
	EventCodeHarvestStart EventCode = 59 // map[0:5270 1:637926215956544319 2:637926215956544319 3:4250 4:16 5:1.6169999 6:5287 7:2195 252:52] - 0 = UserId, 3 = ObjectId, 5: Abbauzeit 7: Abbau-Tool (T8...
	EventCodeHarvestCancel EventCode = 60
	EventCodeHarvestFinished EventCode = 61 // map[0:5270 1:637926215956544319 2:637926215972723131 3:4250 4:1 5:1 7:28 8:[] 9:[] 252:54] - 0: UserId, 3: ObjectId, 4:ItemId 5: Res Standard Quantity 6: Sam...
	EventCodeTakeSilver EventCode = 62 // map[0:-57 1:2178162 2:-57 3:10000000 8:10000 252:55]
	EventCodeRemoveSilver EventCode = 63
	EventCodeActionOnBuildingStart EventCode = 64
	EventCodeActionOnBuildingCancel EventCode = 65
	EventCodeActionOnBuildingFinished EventCode = 66 // Repear: [60]evInstallResourceCancel - map[0:1562 1:63802829 282167 2:442 3:454 4:2 252:60] 0: UserObjectId, 2: ActionId, 4: ActionType
	EventCodeItemRerollQualityFinished EventCode = 67
	EventCodeInstallResourceStart EventCode = 68
	EventCodeInstallResourceCancel EventCode = 69
	EventCodeInstallResourceFinished EventCode = 70
	EventCodeCraftItemFinished EventCode = 71
	EventCodeLogoutCancel EventCode = 72
	EventCodeChatMessage EventCode = 73
	EventCodeChatSay EventCode = 74
	EventCodeChatWhisper EventCode = 75
	EventCodeChatMuted EventCode = 76
	EventCodePlayEmote EventCode = 77
	EventCodeStopEmote EventCode = 78
	EventCodeSystemMessage EventCode = 79
	EventCodeUtilityTextMessage EventCode = 80
	EventCodeUpdateMoney EventCode = 81 // map[0:4195 1:884995625105 252:71] (0: ObjectId, 1: CurrentSilver)
	EventCodeUpdateFame EventCode = 82 // map[0:4195 1:5811910006347 2:100000000 4:10000 6:1 7:427 252:72] (0: ObjectId, 1: TotalPlayerFame, 2: fameWithZoneMultiplier, 3: GroupSize, 4: Multiplier, 5:...
	EventCodeUpdateLearningPoints EventCode = 83
	EventCodeUpdateReSpecPoints EventCode = 84 // map[0:[0 55814284204 0 0 0] 1:1 2:9948534 3:10000000 252:78] 2: GainedReSpec, 3: PaidSilver
	EventCodeUpdateCurrency EventCode = 85
	EventCodeUpdateFactionStanding EventCode = 86
	EventCodeUpdateStanding EventCode = 87 // map[0:11575080 1:3858360 2:970279167 252:81] 0: StandingPoints
	EventCodeRespawn EventCode = 88
	EventCodeServerDebugLog EventCode = 89
	EventCodeCharacterEquipmentChanged EventCode = 90 // map[0:297 1:26283117 2:[0 1721 0 0 0 2330 2301 2468 0 0] 5:[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 3168] 252:85]
	EventCodeRegenerationHealthChanged EventCode = 91
	EventCodeRegenerationEnergyChanged EventCode = 92
	EventCodeRegenerationMountHealthChanged EventCode = 93
	EventCodeRegenerationCraftingChanged EventCode = 94
	EventCodeRegenerationHealthEnergyComboChanged EventCode = 95
	EventCodeRegenerationPlayerComboChanged EventCode = 96
	EventCodeDurabilityChanged EventCode = 97
	EventCodeNewLoot EventCode = 98 // map[0:1863 2:1853 3:Dicky 4:[236.79169 -185.40233] 5:42.864536 6:true 7:1 10:[[-85 -58 82 55 101 -15 76 79 -103 -113 -21 8 -33 46 -99 -28]]
	EventCodeAttachItemContainer EventCode = 99 // map[0:78 1:[-99 -50 125 -49 86 0 -115 74 -74 67 9 101 -87 -71 -66 -10] 3:[0 0 0 0 0 0 656 657] 4:8 252:89] (0: ObjectId, 3: ItemId[])
	EventCodeDetachItemContainer EventCode = 100 // map[0:[-95 72 -77 -75 -70 34 127 73 -114 -96 28 8 75 -107 -106 125] 252:90]
	EventCodeInvalidateItemContainer EventCode = 101
	EventCodeLockItemContainer EventCode = 102
	EventCodeGuildUpdate EventCode = 103
	EventCodeGuildPlayerUpdated EventCode = 104
	EventCodeInvitedToGuild EventCode = 105
	EventCodeGuildMemberWorldUpdate EventCode = 106
	EventCodeUpdateMatchDetails EventCode = 107
	EventCodeObjectEvent EventCode = 108
	EventCodeNewMonolithObject EventCode = 109
	EventCodeMonolithHasBannersPlacedUpdate EventCode = 110
	EventCodeNewOrbObject EventCode = 111
	EventCodeNewCastleObject EventCode = 112
	EventCodeNewSpellEffectArea EventCode = 113
	EventCodeUpdateSpellEffectArea EventCode = 114
	EventCodeNewChainSpell EventCode = 115
	EventCodeUpdateChainSpell EventCode = 116
	EventCodeNewTreasureChest EventCode = 117
	EventCodeStartMatch EventCode = 118
	EventCodeStartArenaMatchInfos EventCode = 119
	EventCodeEndArenaMatch EventCode = 120
	EventCodeMatchUpdate EventCode = 121
	EventCodeActiveMatchUpdate EventCode = 122
	EventCodeNewMob EventCode = 123
	EventCodeDebugAggroInfo EventCode = 124
	EventCodeDebugVariablesInfo EventCode = 125
	EventCodeDebugReputationInfo EventCode = 126
	EventCodeDebugDiminishingReturnInfo EventCode = 127
	EventCodeDebugSmartClusterQueueInfo EventCode = 128
	EventCodeClaimOrbStart EventCode = 129
	EventCodeClaimOrbFinished EventCode = 130
	EventCodeClaimOrbCancel EventCode = 131
	EventCodeOrbUpdate EventCode = 132
	EventCodeOrbClaimed EventCode = 133
	EventCodeOrbReset EventCode = 134
	EventCodeNewWarCampObject EventCode = 135
	EventCodeNewMatchLootChestObject EventCode = 136
	EventCodeNewArenaExit EventCode = 137
	EventCodeGuildMemberTerritoryUpdate EventCode = 138
	EventCodeInvitedMercenaryToMatch EventCode = 139
	EventCodeClusterInfoUpdate EventCode = 140
	EventCodeForcedMovement EventCode = 141
	EventCodeForcedMovementCancel EventCode = 142
	EventCodeCharacterStats EventCode = 143
	EventCodeCharacterStatsKillHistory EventCode = 144
	EventCodeCharacterStatsDeathHistory EventCode = 145
	EventCodeCharacterStatsKnockDownHistory EventCode = 146
	EventCodeCharacterStatsKnockedDownHistory EventCode = 147
	EventCodeGuildStats EventCode = 148
	EventCodeKillHistoryDetails EventCode = 149
	EventCodeItemKillHistoryDetails EventCode = 150
	EventCodeFullAchievementInfo EventCode = 151
	EventCodeFinishedAchievement EventCode = 152
	EventCodeAchievementProgressInfo EventCode = 153
	EventCodeFullAchievementProgressInfo EventCode = 154
	EventCodeFullTrackedAchievementInfo EventCode = 155
	EventCodeFullAutoLearnAchievementInfo EventCode = 156
	EventCodeQuestGiverQuestOffered EventCode = 157
	EventCodeQuestGiverDebugInfo EventCode = 158
	EventCodeConsoleEvent EventCode = 159
	EventCodeTimeSync EventCode = 160
	EventCodeChangeAvatar EventCode = 161
	EventCodeChangeMountSkin EventCode = 162
	EventCodeGameEvent EventCode = 163
	EventCodeKilledPlayer EventCode = 164
	EventCodeDied EventCode = 165
	EventCodeKnockedDown EventCode = 166
	EventCodeUnconcious EventCode = 167
	EventCodeMatchPlayerJoinedEvent EventCode = 168
	EventCodeMatchPlayerStatsEvent EventCode = 169
	EventCodeMatchPlayerStatsCompleteEvent EventCode = 170
	EventCodeMatchTimeLineEventEvent EventCode = 171
	EventCodeMatchNewCombatRound EventCode = 172
	EventCodeMatchEndCombatRound EventCode = 173
	EventCodeMatchPlayerMainGearStatsEvent EventCode = 174
	EventCodeMatchPlayerChangedAvatarEvent EventCode = 175
	EventCodeInvitationPlayerTrade EventCode = 176
	EventCodePlayerTradeStart EventCode = 177
	EventCodePlayerTradeCancel EventCode = 178
	EventCodePlayerTradeUpdate EventCode = 179
	EventCodePlayerTradeFinished EventCode = 180
	EventCodePlayerTradeAcceptChange EventCode = 181
	EventCodeMiniMapPing EventCode = 182
	EventCodeMarketPlaceNotification EventCode = 183
	EventCodeDuellingChallengePlayer EventCode = 184
	EventCodeNewDuellingPost EventCode = 185
	EventCodeDuelStarted EventCode = 186
	EventCodeDuelEnded EventCode = 187
	EventCodeDuelDenied EventCode = 188
	EventCodeDuelRequestCanceled EventCode = 189
	EventCodeDuelLeftArea EventCode = 190
	EventCodeDuelReEnteredArea EventCode = 191
	EventCodeNewRealEstate EventCode = 192
	EventCodeMiniMapOwnedBuildingsPositions EventCode = 193
	EventCodeRealEstateListUpdate EventCode = 194
	EventCodeGuildLogoUpdate EventCode = 195
	EventCodeGuildLogoChanged EventCode = 196
	EventCodePlaceableObjectPlace EventCode = 197
	EventCodePlaceableObjectPlaceCancel EventCode = 198
	EventCodeFurnitureObjectBuffProviderInfo EventCode = 199
	EventCodeFurnitureObjectCheatProviderInfo EventCode = 200
	EventCodeFarmableObjectInfo EventCode = 201
	EventCodeNewUnreadMails EventCode = 202
	EventCodeMailOperationPossible EventCode = 203
	EventCodeGuildLogoObjectUpdate EventCode = 204
	EventCodeStartLogout EventCode = 205
	EventCodeNewChatChannels EventCode = 206
	EventCodeJoinedChatChannel EventCode = 207
	EventCodeLeftChatChannel EventCode = 208
	EventCodeRemovedChatChannel EventCode = 209
	EventCodeAccessStatus EventCode = 210
	EventCodeMounted EventCode = 211
	EventCodeMountStart EventCode = 212
	EventCodeMountCancel EventCode = 213
	EventCodeNewTravelpoint EventCode = 214
	EventCodeNewIslandAccessPoint EventCode = 215
	EventCodeNewExit EventCode = 216
	EventCodeUpdateHome EventCode = 217
	EventCodeUpdateChatSettings EventCode = 218
	EventCodeResurrectionOffer EventCode = 219
	EventCodeResurrectionReply EventCode = 220
	EventCodeLootEquipmentChanged EventCode = 221
	EventCodeUpdateUnlockedGuildLogos EventCode = 222
	EventCodeUpdateUnlockedAvatars EventCode = 223
	EventCodeUpdateUnlockedAvatarRings EventCode = 224
	EventCodeUpdateUnlockedBuildings EventCode = 225
	EventCodeNewIslandManagement EventCode = 226
	EventCodeNewTeleportStone EventCode = 227
	EventCodeCloak EventCode = 228
	EventCodePartyInvitation EventCode = 229
	EventCodePartyJoinRequest EventCode = 230
	EventCodePartyJoined EventCode = 231 // map[0:14368 2:1 3:[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] 4:[[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] [-118 61 -70 72 ...
	EventCodePartyDisbanded EventCode = 232 // map[1:14184 252:213]
	EventCodePartyPlayerJoined EventCode = 233 // map[0:11925 1:[-63 -19 39 16 26 35 -25 67 -111 60 -87 -58 -31 -100 -124 -44] 2:Mitch77 3:1 4:20 5:12 6:-1 7:true 252:214]
	EventCodePartyChangedOrder EventCode = 234
	EventCodePartyPlayerLeft EventCode = 235 // map[0:14368 1:[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] 252:216]
	EventCodePartyLeaderChanged EventCode = 236 // map[0:14595 1:[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] 252:217]
	EventCodePartyLootSettingChangedPlayer EventCode = 237 // map[0:14368 1:1 252:218]
	EventCodePartySilverGained EventCode = 238
	EventCodePartyPlayerUpdated EventCode = 239 // map[0:Bruno313 1:true 3:5 252:221]
	EventCodePartyInvitationAnswer EventCode = 240
	EventCodePartyJoinRequestAnswer EventCode = 241
	EventCodePartyMarkedObjectsUpdated EventCode = 242
	EventCodePartyOnClusterPartyJoined EventCode = 243
	EventCodePartySetRoleFlag EventCode = 244 // map[0:8 1:[-118 61 -70 72 17 -107 121 72 -102 110 20 -25 64 20 106 2] 252:225] (0: FlagType, 1: ObjectId)
	EventCodePartyInviteOrJoinPlayerEquipmentInfo EventCode = 245
	EventCodePartyReadyCheckUpdate EventCode = 246
	EventCodePartyFactionWarfareReinforcementSettingChangedPlayer EventCode = 247
	EventCodeSetPartyNavigation EventCode = 248
	EventCodeEndPartyNavigation EventCode = 249
	EventCodeSpellCooldownUpdate EventCode = 250
	EventCodeNewHellgateExitPortal EventCode = 251
	EventCodeNewExpeditionExit EventCode = 252
	EventCodeNewExpeditionNarrator EventCode = 253
	EventCodeExitEnterStart EventCode = 254
	EventCodeExitEnterCancel EventCode = 255
	EventCodeExitEnterFinished EventCode = 256
	EventCodeNewQuestGiverObject EventCode = 257
	EventCodeFullQuestInfo EventCode = 258
	EventCodeQuestProgressInfo EventCode = 259
	EventCodeQuestGiverInfoForPlayer EventCode = 260
	EventCodeFullExpeditionInfo EventCode = 261
	EventCodeExpeditionQuestProgressInfo EventCode = 262
	EventCodeInvitedToExpedition EventCode = 263
	EventCodeExpeditionRegistrationInfo EventCode = 264
	EventCodeEnteringExpeditionStart EventCode = 265
	EventCodeEnteringExpeditionCancel EventCode = 266
	EventCodeRewardGranted EventCode = 267
	EventCodeArenaRegistrationInfo EventCode = 268
	EventCodeEnteringArenaStart EventCode = 269
	EventCodeEnteringArenaCancel EventCode = 270
	EventCodeEnteringArenaLockStart EventCode = 271
	EventCodeEnteringArenaLockCancel EventCode = 272
	EventCodeInvitedToArenaMatch EventCode = 273
	EventCodeUsingHellgateShrine EventCode = 274
	EventCodeEnteringHellgateLockStart EventCode = 275
	EventCodeEnteringHellgateLockCancel EventCode = 276
	EventCodePlayerCounts EventCode = 277
	EventCodeInCombatStateUpdate EventCode = 278 // map[0:671362 1:true 2:true 252:257] | 1 = true; player hits enemy | 2 = true; enemy hits player
	EventCodeOtherGrabbedLoot EventCode = 279 // LOOT: map[0:424 1:Triky313 2:Bruno313 4:1841 5:1 252:256] | SILVER: map[0:6436 2:Triky313 3:true 5:1550115 252:256] (0: ObjectId, 1: LootedBody, 2: Looter, 4...
	EventCodeTreasureChestUsingStart EventCode = 280
	EventCodeTreasureChestUsingFinished EventCode = 281
	EventCodeTreasureChestUsingCancel EventCode = 282
	EventCodeTreasureChestUsingOpeningComplete EventCode = 283
	EventCodeTreasureChestForceCloseInventory EventCode = 284
	EventCodeLocalTreasuresUpdate EventCode = 285
	EventCodeLootChestSpawnpointsUpdate EventCode = 286
	EventCodePremiumChanged EventCode = 287
	EventCodePremiumExtended EventCode = 288
	EventCodePremiumLifeTimeRewardGained EventCode = 289
	EventCodeGoldPurchased EventCode = 290
	EventCodeLaborerGotUpgraded EventCode = 291
	EventCodeJournalGotFull EventCode = 292
	EventCodeJournalFillError EventCode = 293
	EventCodeFriendRequest EventCode = 294
	EventCodeFriendRequestInfos EventCode = 295
	EventCodeFriendInfos EventCode = 296
	EventCodeFriendRequestAnswered EventCode = 297
	EventCodeFriendOnlineStatus EventCode = 298
	EventCodeFriendRequestCanceled EventCode = 299
	EventCodeFriendRemoved EventCode = 300
	EventCodeFriendUpdated EventCode = 301
	EventCodePartyLootItems EventCode = 302
	EventCodePartyLootItemsRemoved EventCode = 303
	EventCodePartyLootItemTypesRemoved EventCode = 304
	EventCodeReputationUpdate EventCode = 305
	EventCodeDefenseUnitAttackBegin EventCode = 306
	EventCodeDefenseUnitAttackEnd EventCode = 307
	EventCodeDefenseUnitAttackDamage EventCode = 308
	EventCodeUnrestrictedPvpZoneUpdate EventCode = 309
	EventCodeUnrestrictedPvpZoneStatus EventCode = 310
	EventCodeReputationImplicationUpdate EventCode = 311
	EventCodeNewMountObject EventCode = 312
	EventCodeMountHealthUpdate EventCode = 313
	EventCodeMountCooldownUpdate EventCode = 314
	EventCodeNewExpeditionAgent EventCode = 315
	EventCodeNewExpeditionCheckPoint EventCode = 316
	EventCodeExpeditionStartEvent EventCode = 317
	EventCodeVoteEvent EventCode = 318
	EventCodeRatingEvent EventCode = 319
	EventCodeNewArenaAgent EventCode = 320
	EventCodeBoostFarmable EventCode = 321
	EventCodeUseFunction EventCode = 322
	EventCodeNewPortalEntrance EventCode = 323
	EventCodeNewPortalExit EventCode = 324
	EventCodeNewRandomDungeonExit EventCode = 325
	EventCodeWaitingQueueUpdate EventCode = 326
	EventCodePlayerMovementRateUpdate EventCode = 327
	EventCodeObserveStart EventCode = 328
	EventCodeMinimapZergs EventCode = 329
	EventCodeMinimapSmartClusterZergs EventCode = 330
	EventCodePaymentTransactions EventCode = 331
	EventCodePerformanceStatsUpdate EventCode = 332
	EventCodeOverloadModeUpdate EventCode = 333
	EventCodeDebugDrawEvent EventCode = 334
	EventCodeRecordCameraMove EventCode = 335
	EventCodeRecordStart EventCode = 336
	EventCodeClaimPowerCrystalStart EventCode = 337
	EventCodeClaimPowerCrystalCancel EventCode = 338
	EventCodeClaimPowerCrystalReset EventCode = 339
	EventCodeClaimPowerCrystalFinished EventCode = 340
	EventCodeTerritoryClaimStart EventCode = 341
	EventCodeTerritoryClaimCancel EventCode = 342
	EventCodeTerritoryClaimFinished EventCode = 343
	EventCodeTerritoryScheduleResult EventCode = 344
	EventCodeTerritoryUpgradeWithPowerCrystalResult EventCode = 345
	EventCodeReturningPowerCrystalStart EventCode = 346
	EventCodeReturningPowerCrystalFinished EventCode = 347
	EventCodeUpdateAccountState EventCode = 348
	EventCodeStartDeterministicRoam EventCode = 349
	EventCodeGuildFullAccessTagsUpdated EventCode = 350
	EventCodeGuildAccessTagUpdated EventCode = 351
	EventCodeGvgSeasonUpdate EventCode = 352
	EventCodeGvgSeasonCheatCommand EventCode = 353
	EventCodeSeasonPointsByKillingBooster EventCode = 354
	EventCodeFishingStart EventCode = 355
	EventCodeFishingCast EventCode = 356
	EventCodeFishingCatch EventCode = 357
	EventCodeFishingFinished EventCode = 358
	EventCodeFishingCancel EventCode = 359
	EventCodeNewFloatObject EventCode = 360
	EventCodeNewFishingZoneObject EventCode = 361
	EventCodeFishingMiniGame EventCode = 362
	EventCodeSteamAchievementCompleted EventCode = 363
	EventCodeUpdatePuppet EventCode = 364
	EventCodeChangeFlaggingFinished EventCode = 365
	EventCodeNewOutpostObject EventCode = 366
	EventCodeOutpostUpdate EventCode = 367
	EventCodeOutpostClaimed EventCode = 368
	EventCodeOverChargeEnd EventCode = 369
	EventCodeOverChargeStatus EventCode = 370
	EventCodePartyFinderFullUpdate EventCode = 371
	EventCodePartyFinderUpdate EventCode = 372
	EventCodePartyFinderApplicantsUpdate EventCode = 373
	EventCodePartyFinderEquipmentSnapshot EventCode = 374
	EventCodePartyFinderJoinRequestDeclined EventCode = 375
	EventCodeNewUnlockedPersonalSeasonRewards EventCode = 376
	EventCodePersonalSeasonPointsGained EventCode = 377
	EventCodePersonalSeasonPastSeasonDataEvent EventCode = 378
	EventCodeMatchLootChestOpeningStart EventCode = 379
	EventCodeMatchLootChestOpeningFinished EventCode = 380
	EventCodeMatchLootChestOpeningCancel EventCode = 381
	EventCodeNotifyCrystalMatchReward EventCode = 382
	EventCodeCrystalRealmFeedback EventCode = 383
	EventCodeNewLocationMarker EventCode = 384
	EventCodeNewTutorialBlocker EventCode = 385
	EventCodeNewTileSwitch EventCode = 386
	EventCodeNewInformationProvider EventCode = 387
	EventCodeNewDynamicGuildLogo EventCode = 388
	EventCodeNewDecoration EventCode = 389
	EventCodeTutorialUpdate EventCode = 390
	EventCodeTriggerHintBox EventCode = 391
	EventCodeRandomDungeonPositionInfo EventCode = 392
	EventCodeNewLootChest EventCode = 393 // map[0:23 1:[20.5 177.5] 2:423 3:KEEPER_SOLO_BOOKCHEST_STANDARD 4:FOREST_GREEN_LOOTCHEST_KEEPER_SOLO_BOOKCHEST_STANDARD 5:4 6:637734315213820408 7:[] 8:[] 13:...
	EventCodeUpdateLootChest EventCode = 394 // 0=ObjectId, 3=PlayerGuid, 4=PlayerGuid, 7=Free4All map[0:4769 1:5 2:637927794424868192 3:[[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101]] 4:[[-4...
	EventCodeLootChestOpened EventCode = 395 // map[0:23 252:369]
	EventCodeUpdateLootProtectedByMobsWithMinimapDisplay EventCode = 396
	EventCodeNewShrine EventCode = 397 // map[0:19 1:[-89 90] 2:180 3:GENERAL_SHRINE_COMBAT_BUFF 4:SHRINE_NON_COMBAT_BUFF 5:1 6:637734312344532502 252:371]
	EventCodeUpdateShrine EventCode = 398 // map[0:19 1:2 2:637734313445294913 252:372]
	EventCodeUpdateRoom EventCode = 399
	EventCodeNewMobSoul EventCode = 400
	EventCodeNewHellgateShrine EventCode = 401
	EventCodeUpdateHellgateShrine EventCode = 402
	EventCodeActivateHellgateExit EventCode = 403
	EventCodeMutePlayerUpdate EventCode = 404
	EventCodeShopTileUpdate EventCode = 405
	EventCodeShopUpdate EventCode = 406
	EventCodeEasyAntiCheatKick EventCode = 407
	EventCodeBattlEyeServerMessage EventCode = 408
	EventCodeUnlockVanityUnlock EventCode = 409
	EventCodeAvatarUnlocked EventCode = 410
	EventCodeCustomizationChanged EventCode = 411
	EventCodeBaseVaultInfo EventCode = 412
	EventCodeGuildVaultInfo EventCode = 413
	EventCodeBankVaultInfo EventCode = 414 // map[0:6 1:6466931c-65a1-4c5d-870b-8724cf2611dc@3007 2:[] 3:[] 4:[] 5:[] 6:[] 7:[] 8:[] 252:390]
	EventCodeRecoveryVaultPlayerInfo EventCode = 415
	EventCodeRecoveryVaultGuildInfo EventCode = 416
	EventCodeUpdateWardrobe EventCode = 417
	EventCodeCastlePhaseChanged EventCode = 418
	EventCodeGuildAccountLogEvent EventCode = 419
	EventCodeNewHideoutObject EventCode = 420
	EventCodeNewHideoutManagement EventCode = 421
	EventCodeNewHideoutExit EventCode = 422
	EventCodeInitHideoutAttackStart EventCode = 423
	EventCodeInitHideoutAttackCancel EventCode = 424
	EventCodeInitHideoutAttackFinished EventCode = 425
	EventCodeHideoutManagementUpdate EventCode = 426
	EventCodeHideoutUpgradeWithPowerCrystalResult EventCode = 427
	EventCodeIpChanged EventCode = 428
	EventCodeSmartClusterQueueUpdateInfo EventCode = 429
	EventCodeSmartClusterQueueActiveInfo EventCode = 430
	EventCodeSmartClusterQueueKickWarning EventCode = 431
	EventCodeSmartClusterQueueInvite EventCode = 432
	EventCodeReceivedGvgSeasonPoints EventCode = 433
	EventCodeTowerPowerPointUpdate EventCode = 434
	EventCodeOpenWorldAttackScheduleStart EventCode = 435
	EventCodeOpenWorldAttackScheduleFinished EventCode = 436
	EventCodeOpenWorldAttackScheduleCancel EventCode = 437
	EventCodeOpenWorldAttackConquerStart EventCode = 438
	EventCodeOpenWorldAttackConquerFinished EventCode = 439
	EventCodeOpenWorldAttackConquerCancel EventCode = 440
	EventCodeOpenWorldAttackConquerStatus EventCode = 441
	EventCodeOpenWorldAttackStart EventCode = 442
	EventCodeOpenWorldAttackEnd EventCode = 443
	EventCodeNewRandomResourceBlocker EventCode = 444
	EventCodeNewHomeObject EventCode = 445
	EventCodeHideoutObjectUpdate EventCode = 446
	EventCodeUpdateInfamy EventCode = 447
	EventCodeMinimapPositionMarkers EventCode = 448
	EventCodeNewTunnelExit EventCode = 449
	EventCodeCorruptedDungeonUpdate EventCode = 450
	EventCodeCorruptedDungeonStatus EventCode = 451
	EventCodeCorruptedDungeonInfamy EventCode = 452
	EventCodeHellgateRestrictedAreaUpdate EventCode = 453
	EventCodeHellgateInfamy EventCode = 454
	EventCodeHellgateStatus EventCode = 455
	EventCodeHellgateStatusUpdate EventCode = 456
	EventCodeHellgateSuspense EventCode = 457
	EventCodeReplaceSpellSlotWithMultiSpell EventCode = 458
	EventCodeNewCorruptedShrine EventCode = 459
	EventCodeUpdateCorruptedShrine EventCode = 460
	EventCodeCorruptedShrineUsageStart EventCode = 461
	EventCodeCorruptedShrineUsageCancel EventCode = 462
	EventCodeExitUsed EventCode = 463
	EventCodeLinkedToObject EventCode = 464
	EventCodeLinkToObjectBroken EventCode = 465
	EventCodeEstimatedMarketValueUpdate EventCode = 466
	EventCodeStuckCancel EventCode = 467
	EventCodeDungonEscapeReady EventCode = 468
	EventCodeFactionWarfareClusterState EventCode = 469
	EventCodeFactionWarfareHasUnclaimedWeeklyReportsEvent EventCode = 470
	EventCodeSimpleFeedback EventCode = 471
	EventCodeSmartClusterQueueSkipClusterError EventCode = 472
	EventCodeXignCodeEvent EventCode = 473
	EventCodeBatchUseItemStart EventCode = 474
	EventCodeBatchUseItemEnd EventCode = 475
	EventCodeRedZonePlayerNotification EventCode = 476
	EventCodeRedZoneEventCheatCleanup EventCode = 477
	EventCodeRedZoneFortressEventChestOpened EventCode = 478
	EventCodeRedZoneWorldEvent EventCode = 479
	EventCodeFactionWarfareStats EventCode = 480
	EventCodeUpdateFactionBalanceFactors EventCode = 481
	EventCodeFactionEnlistmentChanged EventCode = 482
	EventCodeUpdateFactionRank EventCode = 483
	EventCodeFactionWarfareCampaignRewardsUnlocked EventCode = 484
	EventCodeFeaturedFeatureUpdate EventCode = 485
	EventCodeNewPowerCrystalObject EventCode = 486
	EventCodeMinimapCrystalPositionMarker EventCode = 487
	EventCodeCarryPowerCrystalUpdate EventCode = 488
	EventCodePickupPowerCrystalStart EventCode = 489
	EventCodePickupPowerCrystalCancel EventCode = 490
	EventCodePickupPowerCrystalFinished EventCode = 491
	EventCodeDoSimpleActionStart EventCode = 492
	EventCodeDoSimpleActionCancel EventCode = 493
	EventCodeDoSimpleActionFinished EventCode = 494
	EventCodeNotifyGuestAccountVerified EventCode = 495
	EventCodeMightAndFavorReceivedEvent EventCode = 496 // map[0:63063 2:21021 3:16617 5:5539 6:349680 8:0 252:470] (0: Might, 2: Premium of might, 3: Favor, 5: Premium of favor, 6: Total favor, 8: ???)
	EventCodeWeeklyPvpChallengeRewardStateUpdate EventCode = 497
	EventCodeNewUnlockedPvpSeasonChallengeRewards EventCode = 498
	EventCodeStaticDungeonEntrancesDungeonEventStatusUpdates EventCode = 499
	EventCodeStaticDungeonDungeonValueUpdate EventCode = 500
	EventCodeStaticDungeonEntranceDungeonEventsAborted EventCode = 501
	EventCodeInAppPurchaseConfirmedGooglePlay EventCode = 502
	EventCodeFeatureSwitchInfo EventCode = 503
	EventCodePartyJoinRequestAborted EventCode = 504
	EventCodePartyInviteAborted EventCode = 505
	EventCodePartyStartHuntRequest EventCode = 506
	EventCodePartyStartHuntRequested EventCode = 507
	EventCodePartyStartHuntRequestAnswer EventCode = 508
	EventCodePartyPlayerLeaveScheduled EventCode = 509
	EventCodeGuildInviteDeclined EventCode = 510
	EventCodeCancelMultiSpellSlots EventCode = 511
	EventCodeNewVisualEventObject EventCode = 512
	EventCodeCastleClaimProgress EventCode = 513
	EventCodeCastleClaimProgressLogo EventCode = 514
	EventCodeTownPortalUpdateState EventCode = 515
	EventCodeTownPortalFailed EventCode = 516
	EventCodeConsumableVanityChargesAdded EventCode = 517
	EventCodeFestivitiesUpdate EventCode = 518
	EventCodeNewBannerObject EventCode = 519
	EventCodeNewMistsImmediateReturnExit EventCode = 520
	EventCodeMistsPlayerJoinedInfo EventCode = 521
	EventCodeNewMistsStaticEntrance EventCode = 522
	EventCodeNewMistsOpenWorldExit EventCode = 523
	EventCodeNewTunnelExitTemp EventCode = 524
	EventCodeNewMistsWispSpawn EventCode = 525
	EventCodeMistsWispSpawnStateChange EventCode = 526
	EventCodeNewMistsCityEntrance EventCode = 527
	EventCodeNewMistsCityRoadsEntrance EventCode = 528
	EventCodeMistsCityRoadsEntrancePartyStateUpdate EventCode = 529
	EventCodeMistsCityRoadsEntranceClearStateForParty EventCode = 530
	EventCodeMistsEntranceDataChanged EventCode = 531
	EventCodeNewCagedObject EventCode = 532
	EventCodeCagedObjectStateUpdated EventCode = 533
	EventCodeEntrancePartyBindingCreated EventCode = 534
	EventCodeEntrancePartyBindingCleared EventCode = 535
	EventCodeEntrancePartyBindingInfos EventCode = 536
	EventCodeNewMistsBorderExit EventCode = 537
	EventCodeNewMistsDungeonExit EventCode = 538
	EventCodeLocalQuestInfos EventCode = 539
	EventCodeLocalQuestStarted EventCode = 540
	EventCodeLocalQuestActive EventCode = 541
	EventCodeLocalQuestInactive EventCode = 542
	EventCodeLocalQuestProgressUpdate EventCode = 543
	EventCodeNewUnrestrictedPvpZone EventCode = 544
	EventCodeTemporaryFlaggingStatusUpdate EventCode = 545
	EventCodeSpellTestPerformanceUpdate EventCode = 546
	EventCodeTransformation EventCode = 547
	EventCodeTransformationEnd EventCode = 548
	EventCodeUpdateTrustlevel EventCode = 549
	EventCodeRevealHiddenTimeStamps EventCode = 550
	EventCodeModifyItemTraitFinished EventCode = 551
	EventCodeRerollItemTraitValueFinished EventCode = 552
	EventCodeHuntQuestProgressInfo EventCode = 553
	EventCodeHuntStarted EventCode = 554
	EventCodeHuntFinished EventCode = 555
	EventCodeHuntAborted EventCode = 556
	EventCodeHuntMissionStepStateUpdate EventCode = 557
	EventCodeNewHuntTrack EventCode = 558
	EventCodeHuntMissionUpdate EventCode = 559
	EventCodeHuntQuestMissionProgressUpdate EventCode = 560
	EventCodeHuntTrackUsed EventCode = 561
	EventCodeHuntTrackUseableAgain EventCode = 562
	EventCodeMinimapHuntTrackMarkers EventCode = 563
	EventCodeNoTracksFound EventCode = 564
	EventCodeHuntQuestAborted EventCode = 565
	EventCodeInteractWithTrackStart EventCode = 566
	EventCodeInteractWithTrackCancel EventCode = 567
	EventCodeInteractWithTrackFinished EventCode = 568
	EventCodeNewDynamicCompound EventCode = 569
	EventCodeLegendaryItemDestroyed EventCode = 570
	EventCodeAttunementInfo EventCode = 571 // map[0:T8_MAIN_AXE@4 1:0 2:180810 3:1000000000 252:554] 0: UniqueItemName, 2: GainedAttunement, 3: MaximalAttunementValue
	EventCodeTerritoryClaimRaidedRawEnergyCrystalResult EventCode = 572
	EventCodeCarriedObjectExpiryWarning EventCode = 573
	EventCodeCarriedObjectExpired EventCode = 574
	EventCodeTerritoryRaidStart EventCode = 575
	EventCodeTerritoryRaidCancel EventCode = 576
	EventCodeTerritoryRaidFinished EventCode = 577
	EventCodeTerritoryRaidResult EventCode = 578
	EventCodeTerritoryMonolithActiveRaidStatus EventCode = 579
	EventCodeTerritoryMonolithActiveRaidCancelled EventCode = 580
	EventCodeMonolithEnergyStorageUpdate EventCode = 581
	EventCodeMonolithNextScheduledOpenWorldAttackUpdate EventCode = 582
	EventCodeMonolithProtectedBuildingsDamageReductionUpdate EventCode = 583
	EventCodeNewBuildingBaseEvent EventCode = 584
	EventCodeNewFortificationBuilding EventCode = 585
	EventCodeNewCastleGateBuilding EventCode = 586
	EventCodeBuildingDurabilityUpdate EventCode = 587
	EventCodeMonolithFortificationPointsUpdate EventCode = 588
	EventCodeFortificationBuildingUpgradeInfo EventCode = 589
	EventCodeFortificationBuildingsDamageStateUpdate EventCode = 590
	EventCodeSiegeNotificationEvent EventCode = 591
	EventCodeUpdateEnemyWarBannerActive EventCode = 592
	EventCodeTerritoryAnnouncePlayerEjection EventCode = 593
	EventCodeCastleGateSwitchUseStarted EventCode = 594
	EventCodeCastleGateSwitchUseFinished EventCode = 595
	EventCodeFortificationBuildingWillDowngrade EventCode = 596
	EventCodeBotCommand EventCode = 597
	EventCodeJournalAchievementProgressUpdate EventCode = 598
	EventCodeJournalClaimableRewardUpdate EventCode = 599
	EventCodeKeySync EventCode = 600
	EventCodeLocalQuestAreaGone EventCode = 601
	EventCodeDynamicTemplate EventCode = 602
	EventCodeDynamicTemplateForcedStateChange EventCode = 603
	EventCodeNewOutlandsTeleportationPortal EventCode = 604
	EventCodeNewOutlandsTeleportationReturnPortal EventCode = 605
	EventCodeOutlandsTeleportationBindingCleared EventCode = 606
	EventCodeOutlandsTeleportationReturnPortalUpdateEvent EventCode = 607
	EventCodePlayerUsedOutlandsTeleportationPortal EventCode = 608
	EventCodeEncumberedRestricted EventCode = 609
	EventCodeNewPiledObject EventCode = 610
	EventCodePiledObjectStateChanged EventCode = 611
	EventCodeNewSmugglerCrateDeliveryStation EventCode = 612
	EventCodeKillRewardedNoFame EventCode = 613
	EventCodePickupFromPiledObjectStart EventCode = 614
	EventCodePickupFromPiledObjectCancel EventCode = 615
	EventCodePickupFromPiledObjectReset EventCode = 616
	EventCodePickupFromPiledObjectFinished EventCode = 617
	EventCodeArmoryActivityChange EventCode = 618
	EventCodeNewKillTrophyFurnitureBuilding EventCode = 619
	EventCodeHellDungeonsPlayerJoinedInfo EventCode = 620
	EventCodeNewTileSwitchTrigger EventCode = 621
	EventCodeNewMultiRewardObject EventCode = 622
	EventCodeNewHellDungeonSoulShrineObject EventCode = 623
	EventCodeHellDungeonSoulShrineStateUpdate EventCode = 624
	EventCodeNewResurrectionShrine EventCode = 625
	EventCodeUpdateResurrectionShrine EventCode = 626
	EventCodeStandTimeFinished EventCode = 627
	EventCodeEpicAchievementAndStatsUpdate EventCode = 628
	EventCodeSpectateTargetAfterDeathUpdate EventCode = 629
	EventCodeSpectateTargetAfterDeathEnded EventCode = 630
	EventCodeNewHellDungeonUpwardExit EventCode = 631
	EventCodeNewHellDungeonSoulExit EventCode = 632
	EventCodeNewHellDungeonDownwardExit EventCode = 633
	EventCodeNewHellDungeonChestExit EventCode = 634
	EventCodeNewCorruptedStaticEntrance EventCode = 635
	EventCodeNewHellDungeonStaticEntrance EventCode = 636
	EventCodeUpdateHellDungeonStaticEntranceState EventCode = 637
	EventCodeDebugTriggerHellDungeonShutdownStart EventCode = 638
	EventCodeFullJournalQuestInfo EventCode = 639
	EventCodeJournalQuestProgressInfo EventCode = 640
	EventCodeNewHellDungeonRoomShrineObject EventCode = 641
	EventCodeHellDungeonRoomShrineStateUpdate EventCode = 642
	EventCodeSimpleBehaviourBuildingStateUpdate EventCode = 643
	EventCodeSetTimeScaling EventCode = 644
	EventCodeStopTimeScaling EventCode = 645
	EventCodeKeyValidation EventCode = 646
	EventCodePlayerJoinMapMarkerTimerStates EventCode = 647
	EventCodeNewMapMarkerTimer EventCode = 648
	EventCodeRemoveMapMarkerTimer EventCode = 649
	EventCodeNewFactionFortressObject EventCode = 650
	EventCodeFactionFortressAnnouncePlayerEjection EventCode = 651
	EventCodeRewardFactionWarfareSupply EventCode = 652
	EventCodeFactionCaptureAreaProgressUpdate EventCode = 653
	EventCodeFactionFortressClaimed EventCode = 654
	EventCodeFactionFortressWeaponCachesSpawned EventCode = 655
	EventCodeFactionFortressWeaponCacheClaimed EventCode = 656
	EventCodeFactionFortressFightStateUpdate EventCode = 657
	EventCodeFactionFortressCutoffFightStateUpdate EventCode = 658
	EventCodeFactionFortressFightEnded EventCode = 659
	EventCodeNewFactionWarfarePortal EventCode = 660
	EventCodeFactionPortalTargetUpdate EventCode = 661
	EventCodeFactionFortressFightStartedInRemoteClusterEvent EventCode = 662
	EventCodeFactionFortressFightFinishedInRemoteClusterEvent EventCode = 663
	EventCodeFactionDuchySupplyWarDefensiveVictoryEvent EventCode = 664
	EventCodeFactionDuchyReconnectedFromCutoffEvent EventCode = 665
	EventCodeFactionFortressCutoffFightCancelledByClusterOwnerChangeEvent EventCode = 666
	EventCodeFactionDuchyEnteredCutoffStateEvent EventCode = 667
	EventCodeLeaveProtectionStateUpdate EventCode = 668
	EventCodeRedZoneEventStandings EventCode = 669
	EventCodeNewFactionBattleStandardDeliveryStation EventCode = 670
	EventCodeNewLoreSnippetObject EventCode = 671
	EventCodeLoreSnippetObjectStateUpdate EventCode = 672
	EventCodeLoreSnippedClaimed EventCode = 673
	EventCodeLoreSnippetStatesChangedByCheat EventCode = 674
	EventCodeNewTeleporterNode EventCode = 675
	EventCodeTeleporterNodeStateChanged EventCode = 676
	EventCodeTeleporterConnectionsFullStateUpdate EventCode = 677
	EventCodeTeleporterConnectionStateChanged EventCode = 678
	EventCodeRetrieveCarriableObjectStart EventCode = 679
	EventCodeRetrieveCarriableObjectCancel EventCode = 680
	EventCodeRetrieveCarriableObjectReset EventCode = 681
	EventCodeRetrieveCarriableObjectFinished EventCode = 682
	EventCodeLosingCarriableObjectStart EventCode = 683
	EventCodeLosingCarriableObjectFinished EventCode = 684
	EventCodeNotifyPlatformAccountConfirmed EventCode = 685
)

// EventCodeNames maps a EventCode to its upstream identifier.
var EventCodeNames = map[EventCode]string{
	EventCodeUnused: "Unused",
	EventCodeLeave: "Leave",
	EventCodeJoinFinished: "JoinFinished",
	EventCodeMove: "Move",
	EventCodeTeleport: "Teleport",
	EventCodeChangeEquipment: "ChangeEquipment",
	EventCodeHealthUpdate: "HealthUpdate",
	EventCodeHealthUpdates: "HealthUpdates",
	EventCodeEnergyUpdate: "EnergyUpdate",
	EventCodeDamageShieldUpdate: "DamageShieldUpdate",
	EventCodeCraftingFocusUpdate: "CraftingFocusUpdate",
	EventCodeActiveSpellEffectsUpdate: "ActiveSpellEffectsUpdate",
	EventCodeResetCooldowns: "ResetCooldowns",
	EventCodeAttack: "Attack",
	EventCodeCastStart: "CastStart",
	EventCodeChannelingUpdate: "ChannelingUpdate",
	EventCodeCastCancel: "CastCancel",
	EventCodeCastTimeUpdate: "CastTimeUpdate",
	EventCodeCastFinished: "CastFinished",
	EventCodeCastSpell: "CastSpell",
	EventCodeCastSpells: "CastSpells",
	EventCodeCastHit: "CastHit",
	EventCodeCastHits: "CastHits",
	EventCodeStoredTargetsUpdate: "StoredTargetsUpdate",
	EventCodeChannelingEnded: "ChannelingEnded",
	EventCodeAttackBuilding: "AttackBuilding",
	EventCodeInventoryPutItem: "InventoryPutItem",
	EventCodeInventoryDeleteItem: "InventoryDeleteItem",
	EventCodeInventoryState: "InventoryState",
	EventCodeNewCharacter: "NewCharacter",
	EventCodeNewEquipmentItem: "NewEquipmentItem",
	EventCodeNewSiegeBannerItem: "NewSiegeBannerItem",
	EventCodeNewSimpleItem: "NewSimpleItem",
	EventCodeNewFurnitureItem: "NewFurnitureItem",
	EventCodeNewKillTrophyItem: "NewKillTrophyItem",
	EventCodeNewJournalItem: "NewJournalItem",
	EventCodeNewLaborerItem: "NewLaborerItem",
	EventCodeNewEquipmentItemLegendarySoul: "NewEquipmentItemLegendarySoul",
	EventCodeNewSimpleHarvestableObject: "NewSimpleHarvestableObject",
	EventCodeNewSimpleHarvestableObjectList: "NewSimpleHarvestableObjectList",
	EventCodeNewHarvestableObject: "NewHarvestableObject",
	EventCodeNewTreasureDestinationObject: "NewTreasureDestinationObject",
	EventCodeTreasureDestinationObjectStatus: "TreasureDestinationObjectStatus",
	EventCodeCloseTreasureDestinationObject: "CloseTreasureDestinationObject",
	EventCodeNewSilverObject: "NewSilverObject",
	EventCodeNewBuilding: "NewBuilding",
	EventCodeHarvestableChangeState: "HarvestableChangeState",
	EventCodeMobChangeState: "MobChangeState",
	EventCodeFactionBuildingInfo: "FactionBuildingInfo",
	EventCodeCraftBuildingInfo: "CraftBuildingInfo",
	EventCodeRepairBuildingInfo: "RepairBuildingInfo",
	EventCodeMeldBuildingInfo: "MeldBuildingInfo",
	EventCodeConstructionSiteInfo: "ConstructionSiteInfo",
	EventCodePlayerBuildingInfo: "PlayerBuildingInfo",
	EventCodeFarmBuildingInfo: "FarmBuildingInfo",
	EventCodeTutorialBuildingInfo: "TutorialBuildingInfo",
	EventCodeLaborerObjectInfo: "LaborerObjectInfo",
	EventCodeLaborerObjectJobInfo: "LaborerObjectJobInfo",
	EventCodeMarketPlaceBuildingInfo: "MarketPlaceBuildingInfo",
	EventCodeHarvestStart: "HarvestStart",
	EventCodeHarvestCancel: "HarvestCancel",
	EventCodeHarvestFinished: "HarvestFinished",
	EventCodeTakeSilver: "TakeSilver",
	EventCodeRemoveSilver: "RemoveSilver",
	EventCodeActionOnBuildingStart: "ActionOnBuildingStart",
	EventCodeActionOnBuildingCancel: "ActionOnBuildingCancel",
	EventCodeActionOnBuildingFinished: "ActionOnBuildingFinished",
	EventCodeItemRerollQualityFinished: "ItemRerollQualityFinished",
	EventCodeInstallResourceStart: "InstallResourceStart",
	EventCodeInstallResourceCancel: "InstallResourceCancel",
	EventCodeInstallResourceFinished: "InstallResourceFinished",
	EventCodeCraftItemFinished: "CraftItemFinished",
	EventCodeLogoutCancel: "LogoutCancel",
	EventCodeChatMessage: "ChatMessage",
	EventCodeChatSay: "ChatSay",
	EventCodeChatWhisper: "ChatWhisper",
	EventCodeChatMuted: "ChatMuted",
	EventCodePlayEmote: "PlayEmote",
	EventCodeStopEmote: "StopEmote",
	EventCodeSystemMessage: "SystemMessage",
	EventCodeUtilityTextMessage: "UtilityTextMessage",
	EventCodeUpdateMoney: "UpdateMoney",
	EventCodeUpdateFame: "UpdateFame",
	EventCodeUpdateLearningPoints: "UpdateLearningPoints",
	EventCodeUpdateReSpecPoints: "UpdateReSpecPoints",
	EventCodeUpdateCurrency: "UpdateCurrency",
	EventCodeUpdateFactionStanding: "UpdateFactionStanding",
	EventCodeUpdateStanding: "UpdateStanding",
	EventCodeRespawn: "Respawn",
	EventCodeServerDebugLog: "ServerDebugLog",
	EventCodeCharacterEquipmentChanged: "CharacterEquipmentChanged",
	EventCodeRegenerationHealthChanged: "RegenerationHealthChanged",
	EventCodeRegenerationEnergyChanged: "RegenerationEnergyChanged",
	EventCodeRegenerationMountHealthChanged: "RegenerationMountHealthChanged",
	EventCodeRegenerationCraftingChanged: "RegenerationCraftingChanged",
	EventCodeRegenerationHealthEnergyComboChanged: "RegenerationHealthEnergyComboChanged",
	EventCodeRegenerationPlayerComboChanged: "RegenerationPlayerComboChanged",
	EventCodeDurabilityChanged: "DurabilityChanged",
	EventCodeNewLoot: "NewLoot",
	EventCodeAttachItemContainer: "AttachItemContainer",
	EventCodeDetachItemContainer: "DetachItemContainer",
	EventCodeInvalidateItemContainer: "InvalidateItemContainer",
	EventCodeLockItemContainer: "LockItemContainer",
	EventCodeGuildUpdate: "GuildUpdate",
	EventCodeGuildPlayerUpdated: "GuildPlayerUpdated",
	EventCodeInvitedToGuild: "InvitedToGuild",
	EventCodeGuildMemberWorldUpdate: "GuildMemberWorldUpdate",
	EventCodeUpdateMatchDetails: "UpdateMatchDetails",
	EventCodeObjectEvent: "ObjectEvent",
	EventCodeNewMonolithObject: "NewMonolithObject",
	EventCodeMonolithHasBannersPlacedUpdate: "MonolithHasBannersPlacedUpdate",
	EventCodeNewOrbObject: "NewOrbObject",
	EventCodeNewCastleObject: "NewCastleObject",
	EventCodeNewSpellEffectArea: "NewSpellEffectArea",
	EventCodeUpdateSpellEffectArea: "UpdateSpellEffectArea",
	EventCodeNewChainSpell: "NewChainSpell",
	EventCodeUpdateChainSpell: "UpdateChainSpell",
	EventCodeNewTreasureChest: "NewTreasureChest",
	EventCodeStartMatch: "StartMatch",
	EventCodeStartArenaMatchInfos: "StartArenaMatchInfos",
	EventCodeEndArenaMatch: "EndArenaMatch",
	EventCodeMatchUpdate: "MatchUpdate",
	EventCodeActiveMatchUpdate: "ActiveMatchUpdate",
	EventCodeNewMob: "NewMob",
	EventCodeDebugAggroInfo: "DebugAggroInfo",
	EventCodeDebugVariablesInfo: "DebugVariablesInfo",
	EventCodeDebugReputationInfo: "DebugReputationInfo",
	EventCodeDebugDiminishingReturnInfo: "DebugDiminishingReturnInfo",
	EventCodeDebugSmartClusterQueueInfo: "DebugSmartClusterQueueInfo",
	EventCodeClaimOrbStart: "ClaimOrbStart",
	EventCodeClaimOrbFinished: "ClaimOrbFinished",
	EventCodeClaimOrbCancel: "ClaimOrbCancel",
	EventCodeOrbUpdate: "OrbUpdate",
	EventCodeOrbClaimed: "OrbClaimed",
	EventCodeOrbReset: "OrbReset",
	EventCodeNewWarCampObject: "NewWarCampObject",
	EventCodeNewMatchLootChestObject: "NewMatchLootChestObject",
	EventCodeNewArenaExit: "NewArenaExit",
	EventCodeGuildMemberTerritoryUpdate: "GuildMemberTerritoryUpdate",
	EventCodeInvitedMercenaryToMatch: "InvitedMercenaryToMatch",
	EventCodeClusterInfoUpdate: "ClusterInfoUpdate",
	EventCodeForcedMovement: "ForcedMovement",
	EventCodeForcedMovementCancel: "ForcedMovementCancel",
	EventCodeCharacterStats: "CharacterStats",
	EventCodeCharacterStatsKillHistory: "CharacterStatsKillHistory",
	EventCodeCharacterStatsDeathHistory: "CharacterStatsDeathHistory",
	EventCodeCharacterStatsKnockDownHistory: "CharacterStatsKnockDownHistory",
	EventCodeCharacterStatsKnockedDownHistory: "CharacterStatsKnockedDownHistory",
	EventCodeGuildStats: "GuildStats",
	EventCodeKillHistoryDetails: "KillHistoryDetails",
	EventCodeItemKillHistoryDetails: "ItemKillHistoryDetails",
	EventCodeFullAchievementInfo: "FullAchievementInfo",
	EventCodeFinishedAchievement: "FinishedAchievement",
	EventCodeAchievementProgressInfo: "AchievementProgressInfo",
	EventCodeFullAchievementProgressInfo: "FullAchievementProgressInfo",
	EventCodeFullTrackedAchievementInfo: "FullTrackedAchievementInfo",
	EventCodeFullAutoLearnAchievementInfo: "FullAutoLearnAchievementInfo",
	EventCodeQuestGiverQuestOffered: "QuestGiverQuestOffered",
	EventCodeQuestGiverDebugInfo: "QuestGiverDebugInfo",
	EventCodeConsoleEvent: "ConsoleEvent",
	EventCodeTimeSync: "TimeSync",
	EventCodeChangeAvatar: "ChangeAvatar",
	EventCodeChangeMountSkin: "ChangeMountSkin",
	EventCodeGameEvent: "GameEvent",
	EventCodeKilledPlayer: "KilledPlayer",
	EventCodeDied: "Died",
	EventCodeKnockedDown: "KnockedDown",
	EventCodeUnconcious: "Unconcious",
	EventCodeMatchPlayerJoinedEvent: "MatchPlayerJoinedEvent",
	EventCodeMatchPlayerStatsEvent: "MatchPlayerStatsEvent",
	EventCodeMatchPlayerStatsCompleteEvent: "MatchPlayerStatsCompleteEvent",
	EventCodeMatchTimeLineEventEvent: "MatchTimeLineEventEvent",
	EventCodeMatchNewCombatRound: "MatchNewCombatRound",
	EventCodeMatchEndCombatRound: "MatchEndCombatRound",
	EventCodeMatchPlayerMainGearStatsEvent: "MatchPlayerMainGearStatsEvent",
	EventCodeMatchPlayerChangedAvatarEvent: "MatchPlayerChangedAvatarEvent",
	EventCodeInvitationPlayerTrade: "InvitationPlayerTrade",
	EventCodePlayerTradeStart: "PlayerTradeStart",
	EventCodePlayerTradeCancel: "PlayerTradeCancel",
	EventCodePlayerTradeUpdate: "PlayerTradeUpdate",
	EventCodePlayerTradeFinished: "PlayerTradeFinished",
	EventCodePlayerTradeAcceptChange: "PlayerTradeAcceptChange",
	EventCodeMiniMapPing: "MiniMapPing",
	EventCodeMarketPlaceNotification: "MarketPlaceNotification",
	EventCodeDuellingChallengePlayer: "DuellingChallengePlayer",
	EventCodeNewDuellingPost: "NewDuellingPost",
	EventCodeDuelStarted: "DuelStarted",
	EventCodeDuelEnded: "DuelEnded",
	EventCodeDuelDenied: "DuelDenied",
	EventCodeDuelRequestCanceled: "DuelRequestCanceled",
	EventCodeDuelLeftArea: "DuelLeftArea",
	EventCodeDuelReEnteredArea: "DuelReEnteredArea",
	EventCodeNewRealEstate: "NewRealEstate",
	EventCodeMiniMapOwnedBuildingsPositions: "MiniMapOwnedBuildingsPositions",
	EventCodeRealEstateListUpdate: "RealEstateListUpdate",
	EventCodeGuildLogoUpdate: "GuildLogoUpdate",
	EventCodeGuildLogoChanged: "GuildLogoChanged",
	EventCodePlaceableObjectPlace: "PlaceableObjectPlace",
	EventCodePlaceableObjectPlaceCancel: "PlaceableObjectPlaceCancel",
	EventCodeFurnitureObjectBuffProviderInfo: "FurnitureObjectBuffProviderInfo",
	EventCodeFurnitureObjectCheatProviderInfo: "FurnitureObjectCheatProviderInfo",
	EventCodeFarmableObjectInfo: "FarmableObjectInfo",
	EventCodeNewUnreadMails: "NewUnreadMails",
	EventCodeMailOperationPossible: "MailOperationPossible",
	EventCodeGuildLogoObjectUpdate: "GuildLogoObjectUpdate",
	EventCodeStartLogout: "StartLogout",
	EventCodeNewChatChannels: "NewChatChannels",
	EventCodeJoinedChatChannel: "JoinedChatChannel",
	EventCodeLeftChatChannel: "LeftChatChannel",
	EventCodeRemovedChatChannel: "RemovedChatChannel",
	EventCodeAccessStatus: "AccessStatus",
	EventCodeMounted: "Mounted",
	EventCodeMountStart: "MountStart",
	EventCodeMountCancel: "MountCancel",
	EventCodeNewTravelpoint: "NewTravelpoint",
	EventCodeNewIslandAccessPoint: "NewIslandAccessPoint",
	EventCodeNewExit: "NewExit",
	EventCodeUpdateHome: "UpdateHome",
	EventCodeUpdateChatSettings: "UpdateChatSettings",
	EventCodeResurrectionOffer: "ResurrectionOffer",
	EventCodeResurrectionReply: "ResurrectionReply",
	EventCodeLootEquipmentChanged: "LootEquipmentChanged",
	EventCodeUpdateUnlockedGuildLogos: "UpdateUnlockedGuildLogos",
	EventCodeUpdateUnlockedAvatars: "UpdateUnlockedAvatars",
	EventCodeUpdateUnlockedAvatarRings: "UpdateUnlockedAvatarRings",
	EventCodeUpdateUnlockedBuildings: "UpdateUnlockedBuildings",
	EventCodeNewIslandManagement: "NewIslandManagement",
	EventCodeNewTeleportStone: "NewTeleportStone",
	EventCodeCloak: "Cloak",
	EventCodePartyInvitation: "PartyInvitation",
	EventCodePartyJoinRequest: "PartyJoinRequest",
	EventCodePartyJoined: "PartyJoined",
	EventCodePartyDisbanded: "PartyDisbanded",
	EventCodePartyPlayerJoined: "PartyPlayerJoined",
	EventCodePartyChangedOrder: "PartyChangedOrder",
	EventCodePartyPlayerLeft: "PartyPlayerLeft",
	EventCodePartyLeaderChanged: "PartyLeaderChanged",
	EventCodePartyLootSettingChangedPlayer: "PartyLootSettingChangedPlayer",
	EventCodePartySilverGained: "PartySilverGained",
	EventCodePartyPlayerUpdated: "PartyPlayerUpdated",
	EventCodePartyInvitationAnswer: "PartyInvitationAnswer",
	EventCodePartyJoinRequestAnswer: "PartyJoinRequestAnswer",
	EventCodePartyMarkedObjectsUpdated: "PartyMarkedObjectsUpdated",
	EventCodePartyOnClusterPartyJoined: "PartyOnClusterPartyJoined",
	EventCodePartySetRoleFlag: "PartySetRoleFlag",
	EventCodePartyInviteOrJoinPlayerEquipmentInfo: "PartyInviteOrJoinPlayerEquipmentInfo",
	EventCodePartyReadyCheckUpdate: "PartyReadyCheckUpdate",
	EventCodePartyFactionWarfareReinforcementSettingChangedPlayer: "PartyFactionWarfareReinforcementSettingChangedPlayer",
	EventCodeSetPartyNavigation: "SetPartyNavigation",
	EventCodeEndPartyNavigation: "EndPartyNavigation",
	EventCodeSpellCooldownUpdate: "SpellCooldownUpdate",
	EventCodeNewHellgateExitPortal: "NewHellgateExitPortal",
	EventCodeNewExpeditionExit: "NewExpeditionExit",
	EventCodeNewExpeditionNarrator: "NewExpeditionNarrator",
	EventCodeExitEnterStart: "ExitEnterStart",
	EventCodeExitEnterCancel: "ExitEnterCancel",
	EventCodeExitEnterFinished: "ExitEnterFinished",
	EventCodeNewQuestGiverObject: "NewQuestGiverObject",
	EventCodeFullQuestInfo: "FullQuestInfo",
	EventCodeQuestProgressInfo: "QuestProgressInfo",
	EventCodeQuestGiverInfoForPlayer: "QuestGiverInfoForPlayer",
	EventCodeFullExpeditionInfo: "FullExpeditionInfo",
	EventCodeExpeditionQuestProgressInfo: "ExpeditionQuestProgressInfo",
	EventCodeInvitedToExpedition: "InvitedToExpedition",
	EventCodeExpeditionRegistrationInfo: "ExpeditionRegistrationInfo",
	EventCodeEnteringExpeditionStart: "EnteringExpeditionStart",
	EventCodeEnteringExpeditionCancel: "EnteringExpeditionCancel",
	EventCodeRewardGranted: "RewardGranted",
	EventCodeArenaRegistrationInfo: "ArenaRegistrationInfo",
	EventCodeEnteringArenaStart: "EnteringArenaStart",
	EventCodeEnteringArenaCancel: "EnteringArenaCancel",
	EventCodeEnteringArenaLockStart: "EnteringArenaLockStart",
	EventCodeEnteringArenaLockCancel: "EnteringArenaLockCancel",
	EventCodeInvitedToArenaMatch: "InvitedToArenaMatch",
	EventCodeUsingHellgateShrine: "UsingHellgateShrine",
	EventCodeEnteringHellgateLockStart: "EnteringHellgateLockStart",
	EventCodeEnteringHellgateLockCancel: "EnteringHellgateLockCancel",
	EventCodePlayerCounts: "PlayerCounts",
	EventCodeInCombatStateUpdate: "InCombatStateUpdate",
	EventCodeOtherGrabbedLoot: "OtherGrabbedLoot",
	EventCodeTreasureChestUsingStart: "TreasureChestUsingStart",
	EventCodeTreasureChestUsingFinished: "TreasureChestUsingFinished",
	EventCodeTreasureChestUsingCancel: "TreasureChestUsingCancel",
	EventCodeTreasureChestUsingOpeningComplete: "TreasureChestUsingOpeningComplete",
	EventCodeTreasureChestForceCloseInventory: "TreasureChestForceCloseInventory",
	EventCodeLocalTreasuresUpdate: "LocalTreasuresUpdate",
	EventCodeLootChestSpawnpointsUpdate: "LootChestSpawnpointsUpdate",
	EventCodePremiumChanged: "PremiumChanged",
	EventCodePremiumExtended: "PremiumExtended",
	EventCodePremiumLifeTimeRewardGained: "PremiumLifeTimeRewardGained",
	EventCodeGoldPurchased: "GoldPurchased",
	EventCodeLaborerGotUpgraded: "LaborerGotUpgraded",
	EventCodeJournalGotFull: "JournalGotFull",
	EventCodeJournalFillError: "JournalFillError",
	EventCodeFriendRequest: "FriendRequest",
	EventCodeFriendRequestInfos: "FriendRequestInfos",
	EventCodeFriendInfos: "FriendInfos",
	EventCodeFriendRequestAnswered: "FriendRequestAnswered",
	EventCodeFriendOnlineStatus: "FriendOnlineStatus",
	EventCodeFriendRequestCanceled: "FriendRequestCanceled",
	EventCodeFriendRemoved: "FriendRemoved",
	EventCodeFriendUpdated: "FriendUpdated",
	EventCodePartyLootItems: "PartyLootItems",
	EventCodePartyLootItemsRemoved: "PartyLootItemsRemoved",
	EventCodePartyLootItemTypesRemoved: "PartyLootItemTypesRemoved",
	EventCodeReputationUpdate: "ReputationUpdate",
	EventCodeDefenseUnitAttackBegin: "DefenseUnitAttackBegin",
	EventCodeDefenseUnitAttackEnd: "DefenseUnitAttackEnd",
	EventCodeDefenseUnitAttackDamage: "DefenseUnitAttackDamage",
	EventCodeUnrestrictedPvpZoneUpdate: "UnrestrictedPvpZoneUpdate",
	EventCodeUnrestrictedPvpZoneStatus: "UnrestrictedPvpZoneStatus",
	EventCodeReputationImplicationUpdate: "ReputationImplicationUpdate",
	EventCodeNewMountObject: "NewMountObject",
	EventCodeMountHealthUpdate: "MountHealthUpdate",
	EventCodeMountCooldownUpdate: "MountCooldownUpdate",
	EventCodeNewExpeditionAgent: "NewExpeditionAgent",
	EventCodeNewExpeditionCheckPoint: "NewExpeditionCheckPoint",
	EventCodeExpeditionStartEvent: "ExpeditionStartEvent",
	EventCodeVoteEvent: "VoteEvent",
	EventCodeRatingEvent: "RatingEvent",
	EventCodeNewArenaAgent: "NewArenaAgent",
	EventCodeBoostFarmable: "BoostFarmable",
	EventCodeUseFunction: "UseFunction",
	EventCodeNewPortalEntrance: "NewPortalEntrance",
	EventCodeNewPortalExit: "NewPortalExit",
	EventCodeNewRandomDungeonExit: "NewRandomDungeonExit",
	EventCodeWaitingQueueUpdate: "WaitingQueueUpdate",
	EventCodePlayerMovementRateUpdate: "PlayerMovementRateUpdate",
	EventCodeObserveStart: "ObserveStart",
	EventCodeMinimapZergs: "MinimapZergs",
	EventCodeMinimapSmartClusterZergs: "MinimapSmartClusterZergs",
	EventCodePaymentTransactions: "PaymentTransactions",
	EventCodePerformanceStatsUpdate: "PerformanceStatsUpdate",
	EventCodeOverloadModeUpdate: "OverloadModeUpdate",
	EventCodeDebugDrawEvent: "DebugDrawEvent",
	EventCodeRecordCameraMove: "RecordCameraMove",
	EventCodeRecordStart: "RecordStart",
	EventCodeClaimPowerCrystalStart: "ClaimPowerCrystalStart",
	EventCodeClaimPowerCrystalCancel: "ClaimPowerCrystalCancel",
	EventCodeClaimPowerCrystalReset: "ClaimPowerCrystalReset",
	EventCodeClaimPowerCrystalFinished: "ClaimPowerCrystalFinished",
	EventCodeTerritoryClaimStart: "TerritoryClaimStart",
	EventCodeTerritoryClaimCancel: "TerritoryClaimCancel",
	EventCodeTerritoryClaimFinished: "TerritoryClaimFinished",
	EventCodeTerritoryScheduleResult: "TerritoryScheduleResult",
	EventCodeTerritoryUpgradeWithPowerCrystalResult: "TerritoryUpgradeWithPowerCrystalResult",
	EventCodeReturningPowerCrystalStart: "ReturningPowerCrystalStart",
	EventCodeReturningPowerCrystalFinished: "ReturningPowerCrystalFinished",
	EventCodeUpdateAccountState: "UpdateAccountState",
	EventCodeStartDeterministicRoam: "StartDeterministicRoam",
	EventCodeGuildFullAccessTagsUpdated: "GuildFullAccessTagsUpdated",
	EventCodeGuildAccessTagUpdated: "GuildAccessTagUpdated",
	EventCodeGvgSeasonUpdate: "GvgSeasonUpdate",
	EventCodeGvgSeasonCheatCommand: "GvgSeasonCheatCommand",
	EventCodeSeasonPointsByKillingBooster: "SeasonPointsByKillingBooster",
	EventCodeFishingStart: "FishingStart",
	EventCodeFishingCast: "FishingCast",
	EventCodeFishingCatch: "FishingCatch",
	EventCodeFishingFinished: "FishingFinished",
	EventCodeFishingCancel: "FishingCancel",
	EventCodeNewFloatObject: "NewFloatObject",
	EventCodeNewFishingZoneObject: "NewFishingZoneObject",
	EventCodeFishingMiniGame: "FishingMiniGame",
	EventCodeSteamAchievementCompleted: "SteamAchievementCompleted",
	EventCodeUpdatePuppet: "UpdatePuppet",
	EventCodeChangeFlaggingFinished: "ChangeFlaggingFinished",
	EventCodeNewOutpostObject: "NewOutpostObject",
	EventCodeOutpostUpdate: "OutpostUpdate",
	EventCodeOutpostClaimed: "OutpostClaimed",
	EventCodeOverChargeEnd: "OverChargeEnd",
	EventCodeOverChargeStatus: "OverChargeStatus",
	EventCodePartyFinderFullUpdate: "PartyFinderFullUpdate",
	EventCodePartyFinderUpdate: "PartyFinderUpdate",
	EventCodePartyFinderApplicantsUpdate: "PartyFinderApplicantsUpdate",
	EventCodePartyFinderEquipmentSnapshot: "PartyFinderEquipmentSnapshot",
	EventCodePartyFinderJoinRequestDeclined: "PartyFinderJoinRequestDeclined",
	EventCodeNewUnlockedPersonalSeasonRewards: "NewUnlockedPersonalSeasonRewards",
	EventCodePersonalSeasonPointsGained: "PersonalSeasonPointsGained",
	EventCodePersonalSeasonPastSeasonDataEvent: "PersonalSeasonPastSeasonDataEvent",
	EventCodeMatchLootChestOpeningStart: "MatchLootChestOpeningStart",
	EventCodeMatchLootChestOpeningFinished: "MatchLootChestOpeningFinished",
	EventCodeMatchLootChestOpeningCancel: "MatchLootChestOpeningCancel",
	EventCodeNotifyCrystalMatchReward: "NotifyCrystalMatchReward",
	EventCodeCrystalRealmFeedback: "CrystalRealmFeedback",
	EventCodeNewLocationMarker: "NewLocationMarker",
	EventCodeNewTutorialBlocker: "NewTutorialBlocker",
	EventCodeNewTileSwitch: "NewTileSwitch",
	EventCodeNewInformationProvider: "NewInformationProvider",
	EventCodeNewDynamicGuildLogo: "NewDynamicGuildLogo",
	EventCodeNewDecoration: "NewDecoration",
	EventCodeTutorialUpdate: "TutorialUpdate",
	EventCodeTriggerHintBox: "TriggerHintBox",
	EventCodeRandomDungeonPositionInfo: "RandomDungeonPositionInfo",
	EventCodeNewLootChest: "NewLootChest",
	EventCodeUpdateLootChest: "UpdateLootChest",
	EventCodeLootChestOpened: "LootChestOpened",
	EventCodeUpdateLootProtectedByMobsWithMinimapDisplay: "UpdateLootProtectedByMobsWithMinimapDisplay",
	EventCodeNewShrine: "NewShrine",
	EventCodeUpdateShrine: "UpdateShrine",
	EventCodeUpdateRoom: "UpdateRoom",
	EventCodeNewMobSoul: "NewMobSoul",
	EventCodeNewHellgateShrine: "NewHellgateShrine",
	EventCodeUpdateHellgateShrine: "UpdateHellgateShrine",
	EventCodeActivateHellgateExit: "ActivateHellgateExit",
	EventCodeMutePlayerUpdate: "MutePlayerUpdate",
	EventCodeShopTileUpdate: "ShopTileUpdate",
	EventCodeShopUpdate: "ShopUpdate",
	EventCodeEasyAntiCheatKick: "EasyAntiCheatKick",
	EventCodeBattlEyeServerMessage: "BattlEyeServerMessage",
	EventCodeUnlockVanityUnlock: "UnlockVanityUnlock",
	EventCodeAvatarUnlocked: "AvatarUnlocked",
	EventCodeCustomizationChanged: "CustomizationChanged",
	EventCodeBaseVaultInfo: "BaseVaultInfo",
	EventCodeGuildVaultInfo: "GuildVaultInfo",
	EventCodeBankVaultInfo: "BankVaultInfo",
	EventCodeRecoveryVaultPlayerInfo: "RecoveryVaultPlayerInfo",
	EventCodeRecoveryVaultGuildInfo: "RecoveryVaultGuildInfo",
	EventCodeUpdateWardrobe: "UpdateWardrobe",
	EventCodeCastlePhaseChanged: "CastlePhaseChanged",
	EventCodeGuildAccountLogEvent: "GuildAccountLogEvent",
	EventCodeNewHideoutObject: "NewHideoutObject",
	EventCodeNewHideoutManagement: "NewHideoutManagement",
	EventCodeNewHideoutExit: "NewHideoutExit",
	EventCodeInitHideoutAttackStart: "InitHideoutAttackStart",
	EventCodeInitHideoutAttackCancel: "InitHideoutAttackCancel",
	EventCodeInitHideoutAttackFinished: "InitHideoutAttackFinished",
	EventCodeHideoutManagementUpdate: "HideoutManagementUpdate",
	EventCodeHideoutUpgradeWithPowerCrystalResult: "HideoutUpgradeWithPowerCrystalResult",
	EventCodeIpChanged: "IpChanged",
	EventCodeSmartClusterQueueUpdateInfo: "SmartClusterQueueUpdateInfo",
	EventCodeSmartClusterQueueActiveInfo: "SmartClusterQueueActiveInfo",
	EventCodeSmartClusterQueueKickWarning: "SmartClusterQueueKickWarning",
	EventCodeSmartClusterQueueInvite: "SmartClusterQueueInvite",
	EventCodeReceivedGvgSeasonPoints: "ReceivedGvgSeasonPoints",
	EventCodeTowerPowerPointUpdate: "TowerPowerPointUpdate",
	EventCodeOpenWorldAttackScheduleStart: "OpenWorldAttackScheduleStart",
	EventCodeOpenWorldAttackScheduleFinished: "OpenWorldAttackScheduleFinished",
	EventCodeOpenWorldAttackScheduleCancel: "OpenWorldAttackScheduleCancel",
	EventCodeOpenWorldAttackConquerStart: "OpenWorldAttackConquerStart",
	EventCodeOpenWorldAttackConquerFinished: "OpenWorldAttackConquerFinished",
	EventCodeOpenWorldAttackConquerCancel: "OpenWorldAttackConquerCancel",
	EventCodeOpenWorldAttackConquerStatus: "OpenWorldAttackConquerStatus",
	EventCodeOpenWorldAttackStart: "OpenWorldAttackStart",
	EventCodeOpenWorldAttackEnd: "OpenWorldAttackEnd",
	EventCodeNewRandomResourceBlocker: "NewRandomResourceBlocker",
	EventCodeNewHomeObject: "NewHomeObject",
	EventCodeHideoutObjectUpdate: "HideoutObjectUpdate",
	EventCodeUpdateInfamy: "UpdateInfamy",
	EventCodeMinimapPositionMarkers: "MinimapPositionMarkers",
	EventCodeNewTunnelExit: "NewTunnelExit",
	EventCodeCorruptedDungeonUpdate: "CorruptedDungeonUpdate",
	EventCodeCorruptedDungeonStatus: "CorruptedDungeonStatus",
	EventCodeCorruptedDungeonInfamy: "CorruptedDungeonInfamy",
	EventCodeHellgateRestrictedAreaUpdate: "HellgateRestrictedAreaUpdate",
	EventCodeHellgateInfamy: "HellgateInfamy",
	EventCodeHellgateStatus: "HellgateStatus",
	EventCodeHellgateStatusUpdate: "HellgateStatusUpdate",
	EventCodeHellgateSuspense: "HellgateSuspense",
	EventCodeReplaceSpellSlotWithMultiSpell: "ReplaceSpellSlotWithMultiSpell",
	EventCodeNewCorruptedShrine: "NewCorruptedShrine",
	EventCodeUpdateCorruptedShrine: "UpdateCorruptedShrine",
	EventCodeCorruptedShrineUsageStart: "CorruptedShrineUsageStart",
	EventCodeCorruptedShrineUsageCancel: "CorruptedShrineUsageCancel",
	EventCodeExitUsed: "ExitUsed",
	EventCodeLinkedToObject: "LinkedToObject",
	EventCodeLinkToObjectBroken: "LinkToObjectBroken",
	EventCodeEstimatedMarketValueUpdate: "EstimatedMarketValueUpdate",
	EventCodeStuckCancel: "StuckCancel",
	EventCodeDungonEscapeReady: "DungonEscapeReady",
	EventCodeFactionWarfareClusterState: "FactionWarfareClusterState",
	EventCodeFactionWarfareHasUnclaimedWeeklyReportsEvent: "FactionWarfareHasUnclaimedWeeklyReportsEvent",
	EventCodeSimpleFeedback: "SimpleFeedback",
	EventCodeSmartClusterQueueSkipClusterError: "SmartClusterQueueSkipClusterError",
	EventCodeXignCodeEvent: "XignCodeEvent",
	EventCodeBatchUseItemStart: "BatchUseItemStart",
	EventCodeBatchUseItemEnd: "BatchUseItemEnd",
	EventCodeRedZonePlayerNotification: "RedZonePlayerNotification",
	EventCodeRedZoneEventCheatCleanup: "RedZoneEventCheatCleanup",
	EventCodeRedZoneFortressEventChestOpened: "RedZoneFortressEventChestOpened",
	EventCodeRedZoneWorldEvent: "RedZoneWorldEvent",
	EventCodeFactionWarfareStats: "FactionWarfareStats",
	EventCodeUpdateFactionBalanceFactors: "UpdateFactionBalanceFactors",
	EventCodeFactionEnlistmentChanged: "FactionEnlistmentChanged",
	EventCodeUpdateFactionRank: "UpdateFactionRank",
	EventCodeFactionWarfareCampaignRewardsUnlocked: "FactionWarfareCampaignRewardsUnlocked",
	EventCodeFeaturedFeatureUpdate: "FeaturedFeatureUpdate",
	EventCodeNewPowerCrystalObject: "NewPowerCrystalObject",
	EventCodeMinimapCrystalPositionMarker: "MinimapCrystalPositionMarker",
	EventCodeCarryPowerCrystalUpdate: "CarryPowerCrystalUpdate",
	EventCodePickupPowerCrystalStart: "PickupPowerCrystalStart",
	EventCodePickupPowerCrystalCancel: "PickupPowerCrystalCancel",
	EventCodePickupPowerCrystalFinished: "PickupPowerCrystalFinished",
	EventCodeDoSimpleActionStart: "DoSimpleActionStart",
	EventCodeDoSimpleActionCancel: "DoSimpleActionCancel",
	EventCodeDoSimpleActionFinished: "DoSimpleActionFinished",
	EventCodeNotifyGuestAccountVerified: "NotifyGuestAccountVerified",
	EventCodeMightAndFavorReceivedEvent: "MightAndFavorReceivedEvent",
	EventCodeWeeklyPvpChallengeRewardStateUpdate: "WeeklyPvpChallengeRewardStateUpdate",
	EventCodeNewUnlockedPvpSeasonChallengeRewards: "NewUnlockedPvpSeasonChallengeRewards",
	EventCodeStaticDungeonEntrancesDungeonEventStatusUpdates: "StaticDungeonEntrancesDungeonEventStatusUpdates",
	EventCodeStaticDungeonDungeonValueUpdate: "StaticDungeonDungeonValueUpdate",
	EventCodeStaticDungeonEntranceDungeonEventsAborted: "StaticDungeonEntranceDungeonEventsAborted",
	EventCodeInAppPurchaseConfirmedGooglePlay: "InAppPurchaseConfirmedGooglePlay",
	EventCodeFeatureSwitchInfo: "FeatureSwitchInfo",
	EventCodePartyJoinRequestAborted: "PartyJoinRequestAborted",
	EventCodePartyInviteAborted: "PartyInviteAborted",
	EventCodePartyStartHuntRequest: "PartyStartHuntRequest",
	EventCodePartyStartHuntRequested: "PartyStartHuntRequested",
	EventCodePartyStartHuntRequestAnswer: "PartyStartHuntRequestAnswer",
	EventCodePartyPlayerLeaveScheduled: "PartyPlayerLeaveScheduled",
	EventCodeGuildInviteDeclined: "GuildInviteDeclined",
	EventCodeCancelMultiSpellSlots: "CancelMultiSpellSlots",
	EventCodeNewVisualEventObject: "NewVisualEventObject",
	EventCodeCastleClaimProgress: "CastleClaimProgress",
	EventCodeCastleClaimProgressLogo: "CastleClaimProgressLogo",
	EventCodeTownPortalUpdateState: "TownPortalUpdateState",
	EventCodeTownPortalFailed: "TownPortalFailed",
	EventCodeConsumableVanityChargesAdded: "ConsumableVanityChargesAdded",
	EventCodeFestivitiesUpdate: "FestivitiesUpdate",
	EventCodeNewBannerObject: "NewBannerObject",
	EventCodeNewMistsImmediateReturnExit: "NewMistsImmediateReturnExit",
	EventCodeMistsPlayerJoinedInfo: "MistsPlayerJoinedInfo",
	EventCodeNewMistsStaticEntrance: "NewMistsStaticEntrance",
	EventCodeNewMistsOpenWorldExit: "NewMistsOpenWorldExit",
	EventCodeNewTunnelExitTemp: "NewTunnelExitTemp",
	EventCodeNewMistsWispSpawn: "NewMistsWispSpawn",
	EventCodeMistsWispSpawnStateChange: "MistsWispSpawnStateChange",
	EventCodeNewMistsCityEntrance: "NewMistsCityEntrance",
	EventCodeNewMistsCityRoadsEntrance: "NewMistsCityRoadsEntrance",
	EventCodeMistsCityRoadsEntrancePartyStateUpdate: "MistsCityRoadsEntrancePartyStateUpdate",
	EventCodeMistsCityRoadsEntranceClearStateForParty: "MistsCityRoadsEntranceClearStateForParty",
	EventCodeMistsEntranceDataChanged: "MistsEntranceDataChanged",
	EventCodeNewCagedObject: "NewCagedObject",
	EventCodeCagedObjectStateUpdated: "CagedObjectStateUpdated",
	EventCodeEntrancePartyBindingCreated: "EntrancePartyBindingCreated",
	EventCodeEntrancePartyBindingCleared: "EntrancePartyBindingCleared",
	EventCodeEntrancePartyBindingInfos: "EntrancePartyBindingInfos",
	EventCodeNewMistsBorderExit: "NewMistsBorderExit",
	EventCodeNewMistsDungeonExit: "NewMistsDungeonExit",
	EventCodeLocalQuestInfos: "LocalQuestInfos",
	EventCodeLocalQuestStarted: "LocalQuestStarted",
	EventCodeLocalQuestActive: "LocalQuestActive",
	EventCodeLocalQuestInactive: "LocalQuestInactive",
	EventCodeLocalQuestProgressUpdate: "LocalQuestProgressUpdate",
	EventCodeNewUnrestrictedPvpZone: "NewUnrestrictedPvpZone",
	EventCodeTemporaryFlaggingStatusUpdate: "TemporaryFlaggingStatusUpdate",
	EventCodeSpellTestPerformanceUpdate: "SpellTestPerformanceUpdate",
	EventCodeTransformation: "Transformation",
	EventCodeTransformationEnd: "TransformationEnd",
	EventCodeUpdateTrustlevel: "UpdateTrustlevel",
	EventCodeRevealHiddenTimeStamps: "RevealHiddenTimeStamps",
	EventCodeModifyItemTraitFinished: "ModifyItemTraitFinished",
	EventCodeRerollItemTraitValueFinished: "RerollItemTraitValueFinished",
	EventCodeHuntQuestProgressInfo: "HuntQuestProgressInfo",
	EventCodeHuntStarted: "HuntStarted",
	EventCodeHuntFinished: "HuntFinished",
	EventCodeHuntAborted: "HuntAborted",
	EventCodeHuntMissionStepStateUpdate: "HuntMissionStepStateUpdate",
	EventCodeNewHuntTrack: "NewHuntTrack",
	EventCodeHuntMissionUpdate: "HuntMissionUpdate",
	EventCodeHuntQuestMissionProgressUpdate: "HuntQuestMissionProgressUpdate",
	EventCodeHuntTrackUsed: "HuntTrackUsed",
	EventCodeHuntTrackUseableAgain: "HuntTrackUseableAgain",
	EventCodeMinimapHuntTrackMarkers: "MinimapHuntTrackMarkers",
	EventCodeNoTracksFound: "NoTracksFound",
	EventCodeHuntQuestAborted: "HuntQuestAborted",
	EventCodeInteractWithTrackStart: "InteractWithTrackStart",
	EventCodeInteractWithTrackCancel: "InteractWithTrackCancel",
	EventCodeInteractWithTrackFinished: "InteractWithTrackFinished",
	EventCodeNewDynamicCompound: "NewDynamicCompound",
	EventCodeLegendaryItemDestroyed: "LegendaryItemDestroyed",
	EventCodeAttunementInfo: "AttunementInfo",
	EventCodeTerritoryClaimRaidedRawEnergyCrystalResult: "TerritoryClaimRaidedRawEnergyCrystalResult",
	EventCodeCarriedObjectExpiryWarning: "CarriedObjectExpiryWarning",
	EventCodeCarriedObjectExpired: "CarriedObjectExpired",
	EventCodeTerritoryRaidStart: "TerritoryRaidStart",
	EventCodeTerritoryRaidCancel: "TerritoryRaidCancel",
	EventCodeTerritoryRaidFinished: "TerritoryRaidFinished",
	EventCodeTerritoryRaidResult: "TerritoryRaidResult",
	EventCodeTerritoryMonolithActiveRaidStatus: "TerritoryMonolithActiveRaidStatus",
	EventCodeTerritoryMonolithActiveRaidCancelled: "TerritoryMonolithActiveRaidCancelled",
	EventCodeMonolithEnergyStorageUpdate: "MonolithEnergyStorageUpdate",
	EventCodeMonolithNextScheduledOpenWorldAttackUpdate: "MonolithNextScheduledOpenWorldAttackUpdate",
	EventCodeMonolithProtectedBuildingsDamageReductionUpdate: "MonolithProtectedBuildingsDamageReductionUpdate",
	EventCodeNewBuildingBaseEvent: "NewBuildingBaseEvent",
	EventCodeNewFortificationBuilding: "NewFortificationBuilding",
	EventCodeNewCastleGateBuilding: "NewCastleGateBuilding",
	EventCodeBuildingDurabilityUpdate: "BuildingDurabilityUpdate",
	EventCodeMonolithFortificationPointsUpdate: "MonolithFortificationPointsUpdate",
	EventCodeFortificationBuildingUpgradeInfo: "FortificationBuildingUpgradeInfo",
	EventCodeFortificationBuildingsDamageStateUpdate: "FortificationBuildingsDamageStateUpdate",
	EventCodeSiegeNotificationEvent: "SiegeNotificationEvent",
	EventCodeUpdateEnemyWarBannerActive: "UpdateEnemyWarBannerActive",
	EventCodeTerritoryAnnouncePlayerEjection: "TerritoryAnnouncePlayerEjection",
	EventCodeCastleGateSwitchUseStarted: "CastleGateSwitchUseStarted",
	EventCodeCastleGateSwitchUseFinished: "CastleGateSwitchUseFinished",
	EventCodeFortificationBuildingWillDowngrade: "FortificationBuildingWillDowngrade",
	EventCodeBotCommand: "BotCommand",
	EventCodeJournalAchievementProgressUpdate: "JournalAchievementProgressUpdate",
	EventCodeJournalClaimableRewardUpdate: "JournalClaimableRewardUpdate",
	EventCodeKeySync: "KeySync",
	EventCodeLocalQuestAreaGone: "LocalQuestAreaGone",
	EventCodeDynamicTemplate: "DynamicTemplate",
	EventCodeDynamicTemplateForcedStateChange: "DynamicTemplateForcedStateChange",
	EventCodeNewOutlandsTeleportationPortal: "NewOutlandsTeleportationPortal",
	EventCodeNewOutlandsTeleportationReturnPortal: "NewOutlandsTeleportationReturnPortal",
	EventCodeOutlandsTeleportationBindingCleared: "OutlandsTeleportationBindingCleared",
	EventCodeOutlandsTeleportationReturnPortalUpdateEvent: "OutlandsTeleportationReturnPortalUpdateEvent",
	EventCodePlayerUsedOutlandsTeleportationPortal: "PlayerUsedOutlandsTeleportationPortal",
	EventCodeEncumberedRestricted: "EncumberedRestricted",
	EventCodeNewPiledObject: "NewPiledObject",
	EventCodePiledObjectStateChanged: "PiledObjectStateChanged",
	EventCodeNewSmugglerCrateDeliveryStation: "NewSmugglerCrateDeliveryStation",
	EventCodeKillRewardedNoFame: "KillRewardedNoFame",
	EventCodePickupFromPiledObjectStart: "PickupFromPiledObjectStart",
	EventCodePickupFromPiledObjectCancel: "PickupFromPiledObjectCancel",
	EventCodePickupFromPiledObjectReset: "PickupFromPiledObjectReset",
	EventCodePickupFromPiledObjectFinished: "PickupFromPiledObjectFinished",
	EventCodeArmoryActivityChange: "ArmoryActivityChange",
	EventCodeNewKillTrophyFurnitureBuilding: "NewKillTrophyFurnitureBuilding",
	EventCodeHellDungeonsPlayerJoinedInfo: "HellDungeonsPlayerJoinedInfo",
	EventCodeNewTileSwitchTrigger: "NewTileSwitchTrigger",
	EventCodeNewMultiRewardObject: "NewMultiRewardObject",
	EventCodeNewHellDungeonSoulShrineObject: "NewHellDungeonSoulShrineObject",
	EventCodeHellDungeonSoulShrineStateUpdate: "HellDungeonSoulShrineStateUpdate",
	EventCodeNewResurrectionShrine: "NewResurrectionShrine",
	EventCodeUpdateResurrectionShrine: "UpdateResurrectionShrine",
	EventCodeStandTimeFinished: "StandTimeFinished",
	EventCodeEpicAchievementAndStatsUpdate: "EpicAchievementAndStatsUpdate",
	EventCodeSpectateTargetAfterDeathUpdate: "SpectateTargetAfterDeathUpdate",
	EventCodeSpectateTargetAfterDeathEnded: "SpectateTargetAfterDeathEnded",
	EventCodeNewHellDungeonUpwardExit: "NewHellDungeonUpwardExit",
	EventCodeNewHellDungeonSoulExit: "NewHellDungeonSoulExit",
	EventCodeNewHellDungeonDownwardExit: "NewHellDungeonDownwardExit",
	EventCodeNewHellDungeonChestExit: "NewHellDungeonChestExit",
	EventCodeNewCorruptedStaticEntrance: "NewCorruptedStaticEntrance",
	EventCodeNewHellDungeonStaticEntrance: "NewHellDungeonStaticEntrance",
	EventCodeUpdateHellDungeonStaticEntranceState: "UpdateHellDungeonStaticEntranceState",
	EventCodeDebugTriggerHellDungeonShutdownStart: "DebugTriggerHellDungeonShutdownStart",
	EventCodeFullJournalQuestInfo: "FullJournalQuestInfo",
	EventCodeJournalQuestProgressInfo: "JournalQuestProgressInfo",
	EventCodeNewHellDungeonRoomShrineObject: "NewHellDungeonRoomShrineObject",
	EventCodeHellDungeonRoomShrineStateUpdate: "HellDungeonRoomShrineStateUpdate",
	EventCodeSimpleBehaviourBuildingStateUpdate: "SimpleBehaviourBuildingStateUpdate",
	EventCodeSetTimeScaling: "SetTimeScaling",
	EventCodeStopTimeScaling: "StopTimeScaling",
	EventCodeKeyValidation: "KeyValidation",
	EventCodePlayerJoinMapMarkerTimerStates: "PlayerJoinMapMarkerTimerStates",
	EventCodeNewMapMarkerTimer: "NewMapMarkerTimer",
	EventCodeRemoveMapMarkerTimer: "RemoveMapMarkerTimer",
	EventCodeNewFactionFortressObject: "NewFactionFortressObject",
	EventCodeFactionFortressAnnouncePlayerEjection: "FactionFortressAnnouncePlayerEjection",
	EventCodeRewardFactionWarfareSupply: "RewardFactionWarfareSupply",
	EventCodeFactionCaptureAreaProgressUpdate: "FactionCaptureAreaProgressUpdate",
	EventCodeFactionFortressClaimed: "FactionFortressClaimed",
	EventCodeFactionFortressWeaponCachesSpawned: "FactionFortressWeaponCachesSpawned",
	EventCodeFactionFortressWeaponCacheClaimed: "FactionFortressWeaponCacheClaimed",
	EventCodeFactionFortressFightStateUpdate: "FactionFortressFightStateUpdate",
	EventCodeFactionFortressCutoffFightStateUpdate: "FactionFortressCutoffFightStateUpdate",
	EventCodeFactionFortressFightEnded: "FactionFortressFightEnded",
	EventCodeNewFactionWarfarePortal: "NewFactionWarfarePortal",
	EventCodeFactionPortalTargetUpdate: "FactionPortalTargetUpdate",
	EventCodeFactionFortressFightStartedInRemoteClusterEvent: "FactionFortressFightStartedInRemoteClusterEvent",
	EventCodeFactionFortressFightFinishedInRemoteClusterEvent: "FactionFortressFightFinishedInRemoteClusterEvent",
	EventCodeFactionDuchySupplyWarDefensiveVictoryEvent: "FactionDuchySupplyWarDefensiveVictoryEvent",
	EventCodeFactionDuchyReconnectedFromCutoffEvent: "FactionDuchyReconnectedFromCutoffEvent",
	EventCodeFactionFortressCutoffFightCancelledByClusterOwnerChangeEvent: "FactionFortressCutoffFightCancelledByClusterOwnerChangeEvent",
	EventCodeFactionDuchyEnteredCutoffStateEvent: "FactionDuchyEnteredCutoffStateEvent",
	EventCodeLeaveProtectionStateUpdate: "LeaveProtectionStateUpdate",
	EventCodeRedZoneEventStandings: "RedZoneEventStandings",
	EventCodeNewFactionBattleStandardDeliveryStation: "NewFactionBattleStandardDeliveryStation",
	EventCodeNewLoreSnippetObject: "NewLoreSnippetObject",
	EventCodeLoreSnippetObjectStateUpdate: "LoreSnippetObjectStateUpdate",
	EventCodeLoreSnippedClaimed: "LoreSnippedClaimed",
	EventCodeLoreSnippetStatesChangedByCheat: "LoreSnippetStatesChangedByCheat",
	EventCodeNewTeleporterNode: "NewTeleporterNode",
	EventCodeTeleporterNodeStateChanged: "TeleporterNodeStateChanged",
	EventCodeTeleporterConnectionsFullStateUpdate: "TeleporterConnectionsFullStateUpdate",
	EventCodeTeleporterConnectionStateChanged: "TeleporterConnectionStateChanged",
	EventCodeRetrieveCarriableObjectStart: "RetrieveCarriableObjectStart",
	EventCodeRetrieveCarriableObjectCancel: "RetrieveCarriableObjectCancel",
	EventCodeRetrieveCarriableObjectReset: "RetrieveCarriableObjectReset",
	EventCodeRetrieveCarriableObjectFinished: "RetrieveCarriableObjectFinished",
	EventCodeLosingCarriableObjectStart: "LosingCarriableObjectStart",
	EventCodeLosingCarriableObjectFinished: "LosingCarriableObjectFinished",
	EventCodeNotifyPlatformAccountConfirmed: "NotifyPlatformAccountConfirmed",
}

// String returns the upstream identifier for the EventCode.
func (c EventCode) String() string {
	if n, ok := EventCodeNames[c]; ok {
		return n
	}
	return "EventCode(" + itoa(int(c)) + ")"
}
