// Code generated by tools/codegen; DO NOT EDIT.
// Source: src/StatisticsAnalysisTool/Network/OperationCodes.cs (ref: main)
// Upstream: Triky313/AlbionOnline-StatisticsAnalysis (GPL-3.0)

package protocol

// OperationCode identifies a Photon operation. Values mirror the upstream positional enum.
type OperationCode int

const (
	OperationCodeUnused OperationCode = 0
	OperationCodePing OperationCode = 1
	OperationCodeJoin OperationCode = 2
	OperationCodeVersionedOperation OperationCode = 3
	OperationCodeCreateAccount OperationCode = 4
	OperationCodeLogin OperationCode = 5
	OperationCodeCreateGuestAccount OperationCode = 6
	OperationCodeCreatePlatformOnlyAccount OperationCode = 7
	OperationCodeSendCrashLog OperationCode = 8
	OperationCodeSendTraceRoute OperationCode = 9
	OperationCodeSendVfxStats OperationCode = 10
	OperationCodeSendGamePingInfo OperationCode = 11
	OperationCodeCreateCharacter OperationCode = 12
	OperationCodeDeleteCharacter OperationCode = 13
	OperationCodeSelectCharacter OperationCode = 14
	OperationCodeAcceptPopups OperationCode = 15
	OperationCodeRedeemKeycode OperationCode = 16
	OperationCodeGetGameServerByCluster OperationCode = 17
	OperationCodeGetShopPurchaseUrl OperationCode = 18
	OperationCodeGetReferralSeasonDetails OperationCode = 19
	OperationCodeGetReferralLink OperationCode = 20
	OperationCodeGetShopTilesForCategory OperationCode = 21
	OperationCodeMove OperationCode = 22
	OperationCodeAttackStart OperationCode = 23
	OperationCodeCastStart OperationCode = 24
	OperationCodeCastCancel OperationCode = 25
	OperationCodeTerminateToggleSpell OperationCode = 26
	OperationCodeChannelingCancel OperationCode = 27
	OperationCodeAttackBuildingStart OperationCode = 28
	OperationCodeInventoryDestroyItem OperationCode = 29
	OperationCodeInventoryMoveItem OperationCode = 30 // map[0:4 1:[39 -87 28 -11 -124 -89 51 72 -111 -18 117 74 87 91 -56 72] 2:14 4:[39 -87 28 -11 -124 -89 51 72 -111 -18 117 74 87 91 -56 72] 5:14 253:29]
	OperationCodeInventoryRecoverItem OperationCode = 31
	OperationCodeInventoryRecoverAllItems OperationCode = 32
	OperationCodeInventorySplitStack OperationCode = 33
	OperationCodeInventorySplitStackInto OperationCode = 34
	OperationCodeInventoryStack OperationCode = 35
	OperationCodeInventoryReorder OperationCode = 36
	OperationCodeInventoryDropAll OperationCode = 37
	OperationCodeInventoryAddToStacks OperationCode = 38
	OperationCodeInventoryMoveGivenItems OperationCode = 39
	OperationCodeGetClusterData OperationCode = 40
	OperationCodeChangeCluster OperationCode = 41 // Request: map[0:2 1: 2:[-1] 253:36 255:114] - Response: map[0:4000 253:36 255:114]
	OperationCodeConsoleCommand OperationCode = 42
	OperationCodeChatMessage OperationCode = 43
	OperationCodeReportClientError OperationCode = 44
	OperationCodeRegisterToObject OperationCode = 45
	OperationCodeUnRegisterFromObject OperationCode = 46
	OperationCodeCraftBuildingChangeSettings OperationCode = 47
	OperationCodeCraftBuildingTakeMoney OperationCode = 48
	OperationCodeRepairBuildingChangeSettings OperationCode = 49
	OperationCodeRepairBuildingTakeMoney OperationCode = 50
	OperationCodeActionBuildingChangeSettings OperationCode = 51
	OperationCodeHarvestStart OperationCode = 52
	OperationCodeHarvestCancel OperationCode = 53
	OperationCodeTakeSilver OperationCode = 54
	OperationCodeActionOnBuildingStart OperationCode = 55 // map[0:638028282819317254 1:442 2:2 3:3 4:530000 5:[1571] 253:48]
	OperationCodeActionOnBuildingCancel OperationCode = 56
	OperationCodeInstallResourceStart OperationCode = 57
	OperationCodeInstallResourceCancel OperationCode = 58
	OperationCodeInstallSilver OperationCode = 59
	OperationCodeBuildingFillNutrition OperationCode = 60
	OperationCodeBuildingChangeRenovationState OperationCode = 61
	OperationCodeBuildingBuySkin OperationCode = 62
	OperationCodeBuildingClaim OperationCode = 63
	OperationCodeBuildingGiveup OperationCode = 64
	OperationCodeBuildingNutritionSilverStorageDeposit OperationCode = 65
	OperationCodeBuildingNutritionSilverStorageWithdraw OperationCode = 66
	OperationCodeBuildingNutritionSilverRewardSet OperationCode = 67
	OperationCodeConstructionSiteCreate OperationCode = 68
	OperationCodePlaceableObjectPlace OperationCode = 69
	OperationCodePlaceableObjectPlaceCancel OperationCode = 70
	OperationCodePlaceableObjectPickup OperationCode = 71
	OperationCodeFurnitureObjectUse OperationCode = 72
	OperationCodeFarmableHarvest OperationCode = 73
	OperationCodeFarmableFinishGrownItem OperationCode = 74
	OperationCodeFarmableDestroy OperationCode = 75
	OperationCodeFarmableGetProduct OperationCode = 76
	OperationCodeFarmableFill OperationCode = 77
	OperationCodeTearDownConstructionSite OperationCode = 78
	OperationCodeAuctionCreateOffer OperationCode = 79
	OperationCodeAuctionCreateRequest OperationCode = 80
	OperationCodeAuctionGetOffers OperationCode = 81
	OperationCodeAuctionGetRequests OperationCode = 82
	OperationCodeAuctionBuyOffer OperationCode = 83
	OperationCodeAuctionAbortAuction OperationCode = 84
	OperationCodeAuctionModifyAuction OperationCode = 85
	OperationCodeAuctionAbortOffer OperationCode = 86
	OperationCodeAuctionAbortRequest OperationCode = 87
	OperationCodeAuctionSellRequest OperationCode = 88
	OperationCodeAuctionGetFinishedAuctions OperationCode = 89
	OperationCodeAuctionGetFinishedAuctionsCount OperationCode = 90
	OperationCodeAuctionFetchAuction OperationCode = 91
	OperationCodeAuctionGetMyOpenOffers OperationCode = 92
	OperationCodeAuctionGetMyOpenRequests OperationCode = 93
	OperationCodeAuctionGetMyOpenAuctions OperationCode = 94
	OperationCodeAuctionGetItemAverageStats OperationCode = 95
	OperationCodeAuctionGetItemAverageValue OperationCode = 96
	OperationCodeAuctionGetLowestOfferPrices OperationCode = 97
	OperationCodeContainerOpen OperationCode = 98 // map[0: ObjectId = 405 1:1 2: ObjectGuid = [-46 37 -21 125 -40 -77 125 76 -96 -6 39 120 -46 -21 11 -39] 253:92]
	OperationCodeContainerClose OperationCode = 99
	OperationCodeContainerManageSubContainer OperationCode = 100
	OperationCodeRespawn OperationCode = 101
	OperationCodeSuicide OperationCode = 102
	OperationCodeJoinGuild OperationCode = 103
	OperationCodeLeaveGuild OperationCode = 104
	OperationCodeCreateGuild OperationCode = 105
	OperationCodeInviteToGuild OperationCode = 106
	OperationCodeDeclineGuildInvitation OperationCode = 107
	OperationCodeKickFromGuild OperationCode = 108
	OperationCodeInstantJoinGuild OperationCode = 109
	OperationCodeDuellingChallengePlayer OperationCode = 110
	OperationCodeDuellingAcceptChallenge OperationCode = 111
	OperationCodeDuellingDenyChallenge OperationCode = 112
	OperationCodeChangeClusterTax OperationCode = 113
	OperationCodeClaimTerritory OperationCode = 114
	OperationCodeGiveUpTerritory OperationCode = 115
	OperationCodeChangeTerritoryAccessRights OperationCode = 116
	OperationCodeGetMonolithInfo OperationCode = 117
	OperationCodeGetClaimInfo OperationCode = 118
	OperationCodeGetAttackInfo OperationCode = 119
	OperationCodeGetTerritorySeasonPoints OperationCode = 120
	OperationCodeGetAttackSchedule OperationCode = 121
	OperationCodeGetMatches OperationCode = 122
	OperationCodeGetMatchDetails OperationCode = 123
	OperationCodeJoinMatch OperationCode = 124
	OperationCodeLeaveMatch OperationCode = 125
	OperationCodeGetClusterInstanceInfoForStaticCluster OperationCode = 126
	OperationCodeChangeChatSettings OperationCode = 127
	OperationCodeLogoutStart OperationCode = 128
	OperationCodeLogoutCancel OperationCode = 129
	OperationCodeClaimOrbStart OperationCode = 130
	OperationCodeClaimOrbCancel OperationCode = 131
	OperationCodeMatchLootChestOpeningStart OperationCode = 132
	OperationCodeMatchLootChestOpeningCancel OperationCode = 133
	OperationCodeDepositToGuildAccount OperationCode = 134
	OperationCodeWithdrawalFromAccount OperationCode = 135
	OperationCodeChangeGuildPayUpkeepFlag OperationCode = 136
	OperationCodeChangeGuildTax OperationCode = 137
	OperationCodeGetMyTerritories OperationCode = 138
	OperationCodeMorganaCommand OperationCode = 139
	OperationCodeGetServerInfo OperationCode = 140
	OperationCodeSubscribeToCluster OperationCode = 141
	OperationCodeAnswerMercenaryInvitation OperationCode = 142
	OperationCodeGetCharacterEquipment OperationCode = 143
	OperationCodeGetCharacterSteamAchievements OperationCode = 144
	OperationCodeGetCharacterStats OperationCode = 145
	OperationCodeGetKillHistoryDetails OperationCode = 146
	OperationCodeReSpecAchievement OperationCode = 147
	OperationCodeChangeAvatar OperationCode = 148
	OperationCodeGetRankings OperationCode = 149
	OperationCodeGetRank OperationCode = 150
	OperationCodeGetGvgSeasonRankings OperationCode = 151
	OperationCodeGetGvgSeasonRank OperationCode = 152
	OperationCodeGetGvgSeasonHistoryRankings OperationCode = 153
	OperationCodeGetGvgSeasonGuildMemberHistory OperationCode = 154
	OperationCodeKickFromGvGMatch OperationCode = 155
	OperationCodeGetCrystalLeagueDailySeasonPoints OperationCode = 156
	OperationCodeGetChestLogs OperationCode = 157
	OperationCodeGetAccessRightLogs OperationCode = 158
	OperationCodeGetGuildAccountLogs OperationCode = 159
	OperationCodeGetGuildAccountLogsLargeAmount OperationCode = 160
	OperationCodeInviteToPlayerTrade OperationCode = 161
	OperationCodePlayerTradeCancel OperationCode = 162
	OperationCodePlayerTradeInvitationAccept OperationCode = 163
	OperationCodePlayerTradeAddItem OperationCode = 164
	OperationCodePlayerTradeRemoveItem OperationCode = 165
	OperationCodePlayerTradeAcceptTrade OperationCode = 166
	OperationCodePlayerTradeSetSilverOrGold OperationCode = 167
	OperationCodeSendMiniMapPing OperationCode = 168
	OperationCodeStuck OperationCode = 169
	OperationCodeBuyRealEstate OperationCode = 170
	OperationCodeClaimRealEstate OperationCode = 171
	OperationCodeGiveUpRealEstate OperationCode = 172
	OperationCodeChangeRealEstateOutline OperationCode = 173
	OperationCodeGetMailInfos OperationCode = 174 // map[0:- 2:0 3:[MAIL_ID, MAIL_ID] 4:- 5:- 6:[CLUSTER_ID or UserName] 7:[3 3] 8:[3 3] 9:[true true]
	OperationCodeGetMailCount OperationCode = 175
	OperationCodeReadMail OperationCode = 176 // map[0: MailId 1:QUANTITY|UNIQUE_ITEM_NAME(T4_ARMOR_CLOTH_SET3)|TOTAL_PRICE|UNIT_PRICE 2:[] 3:[] 4:[] 5:[] 6:[] 253:170]
	OperationCodeSendNewMail OperationCode = 177
	OperationCodeDeleteMail OperationCode = 178
	OperationCodeMarkMailUnread OperationCode = 179
	OperationCodeClaimAttachmentFromMail OperationCode = 180
	OperationCodeApplyToGuild OperationCode = 181
	OperationCodeAnswerGuildApplication OperationCode = 182
	OperationCodeRequestGuildFinderFilteredList OperationCode = 183
	OperationCodeUpdateGuildRecruitmentInfo OperationCode = 184
	OperationCodeRequestGuildRecruitmentInfo OperationCode = 185
	OperationCodeRequestGuildFinderNameSearch OperationCode = 186
	OperationCodeRequestGuildFinderRecommendedList OperationCode = 187
	OperationCodeRegisterChatPeer OperationCode = 188
	OperationCodeSendChatMessage OperationCode = 189
	OperationCodeSendModeratorMessage OperationCode = 190
	OperationCodeJoinChatChannel OperationCode = 191
	OperationCodeLeaveChatChannel OperationCode = 192
	OperationCodeSendWhisperMessage OperationCode = 193
	OperationCodeSay OperationCode = 194
	OperationCodePlayEmote OperationCode = 195
	OperationCodeStopEmote OperationCode = 196
	OperationCodeGetClusterMapInfo OperationCode = 197
	OperationCodeAccessRightsChangeSettings OperationCode = 198
	OperationCodeMount OperationCode = 199
	OperationCodeMountCancel OperationCode = 200
	OperationCodeBuyJourney OperationCode = 201
	OperationCodeSetSaleStatusForEstate OperationCode = 202
	OperationCodeResolveGuildOrPlayerName OperationCode = 203
	OperationCodeGetRespawnInfos OperationCode = 204
	OperationCodeMakeHome OperationCode = 205
	OperationCodeLeaveHome OperationCode = 206
	OperationCodeResurrectionReply OperationCode = 207
	OperationCodeAllianceCreate OperationCode = 208
	OperationCodeAllianceDisband OperationCode = 209
	OperationCodeAllianceGetMemberInfos OperationCode = 210
	OperationCodeAllianceInvite OperationCode = 211
	OperationCodeAllianceAnswerInvitation OperationCode = 212
	OperationCodeAllianceCancelInvitation OperationCode = 213
	OperationCodeAllianceKickGuild OperationCode = 214
	OperationCodeAllianceLeave OperationCode = 215
	OperationCodeAllianceChangeGoldPaymentFlag OperationCode = 216
	OperationCodeAllianceGetDetailInfo OperationCode = 217
	OperationCodeGetIslandInfos OperationCode = 218
	OperationCodeBuyMyIsland OperationCode = 219
	OperationCodeBuyGuildIsland OperationCode = 220
	OperationCodeUpgradeMyIsland OperationCode = 221
	OperationCodeUpgradeGuildIsland OperationCode = 222
	OperationCodeTerritoryFillNutrition OperationCode = 223
	OperationCodeTeleportBack OperationCode = 224
	OperationCodePartyInvitePlayer OperationCode = 225
	OperationCodePartyRequestJoin OperationCode = 226
	OperationCodePartyAnswerInvitation OperationCode = 227
	OperationCodePartyAnswerJoinRequest OperationCode = 228
	OperationCodePartyLeave OperationCode = 229
	OperationCodePartyKickPlayer OperationCode = 230
	OperationCodePartyMakeLeader OperationCode = 231
	OperationCodePartyChangeLootSetting OperationCode = 232
	OperationCodePartyMarkObject OperationCode = 233
	OperationCodePartySetRole OperationCode = 234
	OperationCodePartyChangeFactionWarfareRequestReinforcementsSetting OperationCode = 235
	OperationCodeSetGuildCodex OperationCode = 236
	OperationCodeExitEnterStart OperationCode = 237
	OperationCodeExitEnterCancel OperationCode = 238
	OperationCodeQuestGiverRequest OperationCode = 239
	OperationCodeGoldMarketGetBuyOffer OperationCode = 240
	OperationCodeGoldMarketGetBuyOfferFromSilver OperationCode = 241
	OperationCodeGoldMarketGetSellOffer OperationCode = 242
	OperationCodeGoldMarketGetSellOfferFromSilver OperationCode = 243
	OperationCodeGoldMarketBuyGold OperationCode = 244
	OperationCodeGoldMarketSellGold OperationCode = 245
	OperationCodeGoldMarketCreateSellOrder OperationCode = 246
	OperationCodeGoldMarketCreateBuyOrder OperationCode = 247
	OperationCodeGoldMarketGetInfos OperationCode = 248
	OperationCodeGoldMarketCancelOrder OperationCode = 249
	OperationCodeGoldMarketGetAverageInfo OperationCode = 250
	OperationCodeTreasureChestUsingStart OperationCode = 251
	OperationCodeTreasureChestUsingCancel OperationCode = 252
	OperationCodeUseLootChest OperationCode = 253 // <- LootLogger: https://github.com/EmeraldKnight79/AO-DU-LootLogger/blob/b1ab099e0d82bdee0a87c153f4bbae324295656e/LootLogger/PacketHandler.cs#L68
	OperationCodeUseShrine OperationCode = 254
	OperationCodeUseHellgateShrine OperationCode = 255
	OperationCodeGetSiegeBannerInfo OperationCode = 256
	OperationCodeLaborerStartJob OperationCode = 257
	OperationCodeLaborerTakeJobLoot OperationCode = 258
	OperationCodeLaborerDismiss OperationCode = 259
	OperationCodeLaborerMove OperationCode = 260
	OperationCodeLaborerBuyItem OperationCode = 261
	OperationCodeLaborerUpgrade OperationCode = 262
	OperationCodeBuyPremium OperationCode = 263
	OperationCodeRealEstateGetAuctionData OperationCode = 264
	OperationCodeRealEstateBidOnAuction OperationCode = 265
	OperationCodeFriendInvite OperationCode = 266
	OperationCodeFriendAnswerInvitation OperationCode = 267
	OperationCodeFriendCancelnvitation OperationCode = 268
	OperationCodeFriendRemove OperationCode = 269
	OperationCodeEquipmentItemChangeSpell OperationCode = 270
	OperationCodeExpeditionRegister OperationCode = 271
	OperationCodeExpeditionRegisterCancel OperationCode = 272
	OperationCodeJoinExpedition OperationCode = 273
	OperationCodeDeclineExpeditionInvitation OperationCode = 274
	OperationCodeVoteStart OperationCode = 275
	OperationCodeVoteDoVote OperationCode = 276
	OperationCodeRatingDoRate OperationCode = 277
	OperationCodeEnteringExpeditionStart OperationCode = 278
	OperationCodeEnteringExpeditionCancel OperationCode = 279
	OperationCodeActivateExpeditionCheckPoint OperationCode = 280
	OperationCodeArenaRegister OperationCode = 281
	OperationCodeArenaAddInvite OperationCode = 282
	OperationCodeArenaRegisterCancel OperationCode = 283
	OperationCodeArenaLeave OperationCode = 284
	OperationCodeJoinArenaMatch OperationCode = 285
	OperationCodeDeclineArenaInvitation OperationCode = 286
	OperationCodeEnteringArenaStart OperationCode = 287
	OperationCodeEnteringArenaCancel OperationCode = 288
	OperationCodeArenaCustomMatch OperationCode = 289
	OperationCodeUpdateCharacterStatement OperationCode = 290
	OperationCodeBoostFarmable OperationCode = 291
	OperationCodeGetStrikeHistory OperationCode = 292
	OperationCodeUseFunction OperationCode = 293
	OperationCodeUsePortalEntrance OperationCode = 294
	OperationCodeResetPortalBinding OperationCode = 295
	OperationCodeQueryPortalBinding OperationCode = 296
	OperationCodeClaimPaymentTransaction OperationCode = 297
	OperationCodeChangeUseFlag OperationCode = 298
	OperationCodeClientPerformanceStats OperationCode = 299
	OperationCodeExtendedHardwareStats OperationCode = 300 // map[0:NVIDIA GeForce RTX 3090 1:AMD Ryzen 7 2700X Eight-Core Processor  2:Windows 10  (10.0.0) 64bit 3:3693 4:24348 5:16293 6:DE-DE 7:Custom 8:1746 10:-1 253...
	OperationCodeClientLowMemoryWarning OperationCode = 301
	OperationCodeTerritoryClaimStart OperationCode = 302
	OperationCodeTerritoryClaimCancel OperationCode = 303
	OperationCodeDeliverCarriableObjectStart OperationCode = 304
	OperationCodeDeliverCarriableObjectCancel OperationCode = 305
	OperationCodeTerritoryUpgradeWithPowerCrystal OperationCode = 306
	OperationCodeRequestAppStoreProducts OperationCode = 307
	OperationCodeVerifyProductPurchase OperationCode = 308
	OperationCodeQueryGuildPlayerStats OperationCode = 309
	OperationCodeQueryAllianceGuildStats OperationCode = 310
	OperationCodeTrackAchievements OperationCode = 311
	OperationCodeSetAchievementsAutoLearn OperationCode = 312
	OperationCodeDepositItemToGuildCurrency OperationCode = 313
	OperationCodeWithdrawalItemFromGuildCurrency OperationCode = 314
	OperationCodeAuctionSellSpecificItemRequest OperationCode = 315
	OperationCodeFishingStart OperationCode = 316 // 0: EventId, 2: Used fishing rod
	OperationCodeFishingCasting OperationCode = 317
	OperationCodeFishingCast OperationCode = 318
	OperationCodeFishingCatch OperationCode = 319
	OperationCodeFishingPull OperationCode = 320
	OperationCodeFishingGiveLine OperationCode = 321
	OperationCodeFishingFinish OperationCode = 322 // Request: 1: true is finished | false is failed - Response: Fishing finished
	OperationCodeFishingCancel OperationCode = 323 // Request: Fishing canceled
	OperationCodeCreateGuildAccessTag OperationCode = 324
	OperationCodeDeleteGuildAccessTag OperationCode = 325
	OperationCodeRenameGuildAccessTag OperationCode = 326
	OperationCodeFlagGuildAccessTagGuildPermission OperationCode = 327
	OperationCodeAssignGuildAccessTag OperationCode = 328
	OperationCodeRemoveGuildAccessTagFromPlayer OperationCode = 329
	OperationCodeModifyGuildAccessTagEditors OperationCode = 330
	OperationCodeRequestPublicAccessTags OperationCode = 331
	OperationCodeChangeAccessTagPublicFlag OperationCode = 332
	OperationCodeUpdateGuildAccessTag OperationCode = 333
	OperationCodeSteamStartMicrotransaction OperationCode = 334
	OperationCodeSteamFinishMicrotransaction OperationCode = 335
	OperationCodeRequestXboxPurchaseIntent OperationCode = 336
	OperationCodeCloseXboxPurchaseIntent OperationCode = 337
	OperationCodeSteamIdHasActiveAccount OperationCode = 338
	OperationCodeCheckEmailAccountState OperationCode = 339
	OperationCodeLinkAccountToSteamId OperationCode = 340
	OperationCodeEpicIdHasActiveAccount OperationCode = 341
	OperationCodeLinkAccountToEpicId OperationCode = 342
	OperationCodeXboxIdHasActiveAccount OperationCode = 343
	OperationCodeInAppConfirmPaymentGooglePlay OperationCode = 344
	OperationCodeInAppConfirmPaymentAppleAppStore OperationCode = 345
	OperationCodeInAppPurchaseRequest OperationCode = 346
	OperationCodeInAppPurchaseFailed OperationCode = 347
	OperationCodeCharacterSubscriptionInfo OperationCode = 348
	OperationCodeAccountSubscriptionInfo OperationCode = 349
	OperationCodeBuyGvgSeasonBooster OperationCode = 350
	OperationCodeChangeFlaggingPrepare OperationCode = 351
	OperationCodeOverCharge OperationCode = 352
	OperationCodeOverChargeEnd OperationCode = 353
	OperationCodeRequestTrusted OperationCode = 354
	OperationCodeChangeGuildLogo OperationCode = 355
	OperationCodePartyFinderRegisterForUpdates OperationCode = 356
	OperationCodePartyFinderUnregisterForUpdates OperationCode = 357
	OperationCodePartyFinderEnlistNewPartySearch OperationCode = 358
	OperationCodePartyFinderDeletePartySearch OperationCode = 359
	OperationCodePartyFinderChangePartySearch OperationCode = 360
	OperationCodePartyFinderChangeRole OperationCode = 361
	OperationCodePartyFinderApplyForGroup OperationCode = 362
	OperationCodePartyFinderAcceptOrDeclineApplyForGroup OperationCode = 363
	OperationCodePartyFinderGetEquipmentSnapshot OperationCode = 364
	OperationCodePartyFinderRegisterApplicants OperationCode = 365
	OperationCodePartyFinderUnregisterApplicants OperationCode = 366
	OperationCodePartyFinderFulltextSearch OperationCode = 367
	OperationCodePartyFinderRequestEquipmentSnapshot OperationCode = 368
	OperationCodeGetPersonalSeasonTrackerData OperationCode = 369
	OperationCodeGetPersonalSeasonPastRewardData OperationCode = 370
	OperationCodeUseConsumableFromInventory OperationCode = 371
	OperationCodeClaimPersonalSeasonReward OperationCode = 372
	OperationCodeXignCodeMessageToServer OperationCode = 373
	OperationCodeBattlEyeMessageToServer OperationCode = 374
	OperationCodeSetNextTutorialState OperationCode = 375
	OperationCodeAddPlayerToMuteList OperationCode = 376
	OperationCodeRemovePlayerFromMuteList OperationCode = 377
	OperationCodeProductShopUserEvent OperationCode = 378
	OperationCodeGetVanityUnlocks OperationCode = 379
	OperationCodeBuyVanityUnlocks OperationCode = 380
	OperationCodeGetMountSkins OperationCode = 381
	OperationCodeSetMountSkin OperationCode = 382
	OperationCodeSetWardrobe OperationCode = 383
	OperationCodeChangeCustomization OperationCode = 384
	OperationCodeChangePlayerIslandData OperationCode = 385
	OperationCodeGetGuildChallengePoints OperationCode = 386
	OperationCodeSmartQueueJoin OperationCode = 387
	OperationCodeSmartQueueLeave OperationCode = 388
	OperationCodeSmartQueueSelectSpawnCluster OperationCode = 389
	OperationCodeUpgradeHideout OperationCode = 390
	OperationCodeInitHideoutAttackStart OperationCode = 391
	OperationCodeInitHideoutAttackCancel OperationCode = 392
	OperationCodeHideoutFillNutrition OperationCode = 393
	OperationCodeHideoutGetInfo OperationCode = 394
	OperationCodeHideoutGetOwnerInfo OperationCode = 395
	OperationCodeHideoutSetTribute OperationCode = 396
	OperationCodeHideoutUpgradeWithPowerCrystal OperationCode = 397
	OperationCodeHideoutDeclareHQ OperationCode = 398
	OperationCodeHideoutUndeclareHQ OperationCode = 399
	OperationCodeHideoutGetHQRequirements OperationCode = 400
	OperationCodeHideoutBoost OperationCode = 401
	OperationCodeHideoutBoostConstruction OperationCode = 402
	OperationCodeOpenWorldAttackScheduleStart OperationCode = 403
	OperationCodeOpenWorldAttackScheduleCancel OperationCode = 404
	OperationCodeOpenWorldAttackConquerStart OperationCode = 405
	OperationCodeOpenWorldAttackConquerCancel OperationCode = 406
	OperationCodeGetOpenWorldAttackDetails OperationCode = 407
	OperationCodeGetNextOpenWorldAttackScheduleTime OperationCode = 408
	OperationCodeRecoverVaultFromHideout OperationCode = 409
	OperationCodeGetGuildEnergyDrainInfo OperationCode = 410
	OperationCodeChannelingUpdate OperationCode = 411
	OperationCodeUseCorruptedShrine OperationCode = 412
	OperationCodeRequestEstimatedMarketValue OperationCode = 413
	OperationCodeLogFeedback OperationCode = 414
	OperationCodeGetInfamyInfo OperationCode = 415
	OperationCodeGetPartySmartClusterQueuePriority OperationCode = 416
	OperationCodeSetPartySmartClusterQueuePriority OperationCode = 417
	OperationCodeClientAntiAutoClickerInfo OperationCode = 418
	OperationCodeClientBotPatternDetectionInfo OperationCode = 419
	OperationCodeClientAntiGatherClickerInfo OperationCode = 420
	OperationCodeLoadoutCreate OperationCode = 421
	OperationCodeLoadoutRead OperationCode = 422
	OperationCodeLoadoutReadHeaders OperationCode = 423
	OperationCodeLoadoutUpdate OperationCode = 424
	OperationCodeLoadoutDelete OperationCode = 425
	OperationCodeLoadoutOrderUpdate OperationCode = 426
	OperationCodeLoadoutEquip OperationCode = 427
	OperationCodeBatchUseItemCancel OperationCode = 428
	OperationCodeEnlistFactionWarfare OperationCode = 429
	OperationCodeGetFactionWarfareWeeklyReport OperationCode = 430
	OperationCodeClaimFactionWarfareWeeklyReport OperationCode = 431
	OperationCodeGetFactionWarfareCampaignData OperationCode = 432
	OperationCodeClaimFactionWarfareItemReward OperationCode = 433
	OperationCodeSendMemoryConsumption OperationCode = 434
	OperationCodePickupCarriableObjectStart OperationCode = 435
	OperationCodePickupCarriableObjectCancel OperationCode = 436
	OperationCodeSetSavingChestLogsFlag OperationCode = 437
	OperationCodeGetSavingChestLogsFlag OperationCode = 438
	OperationCodeRegisterGuestAccount OperationCode = 439
	OperationCodeResendGuestAccountVerificationEmail OperationCode = 440
	OperationCodeDoSimpleActionStart OperationCode = 441
	OperationCodeDoSimpleActionCancel OperationCode = 442
	OperationCodeGetGvgSeasonContributionByActivity OperationCode = 443
	OperationCodeGetGvgSeasonContributionByCrystalLeague OperationCode = 444
	OperationCodeGetGuildMightCategoryContribution OperationCode = 445
	OperationCodeGetGuildMightCategoryOverview OperationCode = 446
	OperationCodeGetPvpChallengeData OperationCode = 447
	OperationCodeClaimPvpChallengeWeeklyReward OperationCode = 448
	OperationCodeGetPersonalMightStats OperationCode = 449
	OperationCodeGetPvpChallengeSeasonRewards OperationCode = 450
	OperationCodeGetPvpChallengeSeasonRewardItems OperationCode = 451
	OperationCodeClaimPvpChallengeSeasonRewards OperationCode = 452
	OperationCodeClaimPvpChallengeSeasonRewardItems OperationCode = 453
	OperationCodeAuctionGetLoadoutOffers OperationCode = 454
	OperationCodeAuctionBuyLoadoutOffer OperationCode = 455
	OperationCodeAccountDeletionRequest OperationCode = 456
	OperationCodeAccountReactivationRequest OperationCode = 457
	OperationCodeCreateModeratorNotesForAccount OperationCode = 458
	OperationCodeGetModeratorNotesForAccount OperationCode = 459
	OperationCodeGetModerationEscalationDefiniton OperationCode = 460
	OperationCodeEventBasedPopupAddSeen OperationCode = 461
	OperationCodeGetItemKillHistory OperationCode = 462
	OperationCodeGetVanityConsumables OperationCode = 463
	OperationCodeEquipKillEmote OperationCode = 464
	OperationCodeChangeKillEmotePlayOnKnockdownSetting OperationCode = 465
	OperationCodeBuyVanityConsumableCharges OperationCode = 466
	OperationCodeReclaimVanityItem OperationCode = 467
	OperationCodeGetArenaRankings OperationCode = 468
	OperationCodeGetCrystalLeagueStatistics OperationCode = 469
	OperationCodeSendOptionsLog OperationCode = 470
	OperationCodeSendControlsOptionsLog OperationCode = 471
	OperationCodeMistsUseImmediateReturnExit OperationCode = 472
	OperationCodeMistsUseStaticEntrance OperationCode = 473
	OperationCodeMistsUseCityRoadsEntrance OperationCode = 474
	OperationCodeChangeNewGuildMemberMail OperationCode = 475
	OperationCodeGetNewGuildMemberMail OperationCode = 476
	OperationCodeChangeGuildFactionAllegiance OperationCode = 477
	OperationCodeGetGuildFactionAllegiance OperationCode = 478
	OperationCodeGuildBannerChange OperationCode = 479
	OperationCodeGuildGetOptionalStats OperationCode = 480
	OperationCodeGuildSetOptionalStats OperationCode = 481
	OperationCodeGetPlayerInfoForStalk OperationCode = 482
	OperationCodePayGoldForCharacterTypeChange OperationCode = 483
	OperationCodeQuickSellAuctionQueryAction OperationCode = 484
	OperationCodeQuickSellAuctionSellAction OperationCode = 485
	OperationCodeFcmTokenToServer OperationCode = 486
	OperationCodeApnsTokenToServer OperationCode = 487
	OperationCodeDeathRecap OperationCode = 488
	OperationCodeAuctionFetchFinishedAuctions OperationCode = 489
	OperationCodeAbortAuctionFetchFinishedAuctions OperationCode = 490
	OperationCodeRequestLegendaryEvenHistory OperationCode = 491
	OperationCodePartyAnswerStartHuntRequest OperationCode = 492
	OperationCodeHuntAbort OperationCode = 493
	OperationCodeUseFindTrackSpellFromItemPrepare OperationCode = 494
	OperationCodeInteractWithTrackStart OperationCode = 495
	OperationCodeInteractWithTrackCancel OperationCode = 496
	OperationCodeTerritoryRaidStart OperationCode = 497
	OperationCodeTerritoryRaidCancel OperationCode = 498
	OperationCodeTerritoryClaimRaidedRawEnergyCrystalResult OperationCode = 499
	OperationCodeGvGSeasonPlayerGuildParticipationDetails OperationCode = 500
	OperationCodeDailyMightBonus OperationCode = 501
	OperationCodeClaimDailyMightBonus OperationCode = 502
	OperationCodeGetFortificationGroupInfo OperationCode = 503
	OperationCodeUpgradeFortificationGroup OperationCode = 504
	OperationCodeCancelUpgradeFortificationGroup OperationCode = 505
	OperationCodeDowngradeFortificationGroup OperationCode = 506
	OperationCodeGetClusterActivityChestEstimates OperationCode = 507
	OperationCodePartyReadyCheckBegin OperationCode = 508
	OperationCodePartyReadyCheckUpdate OperationCode = 509
	OperationCodeClaimAlbionJournalReward OperationCode = 510
	OperationCodeTrackAlbionJournalAchievements OperationCode = 511
	OperationCodeTrackAlbionJournalAchievementSubCategory OperationCode = 512
	OperationCodeRequestOutlandsTeleportationUsage OperationCode = 513
	OperationCodePickupFromPiledObjectStart OperationCode = 514
	OperationCodePickupFromPiledObjectCancel OperationCode = 515
	OperationCodeAssetOverview OperationCode = 516
	OperationCodeAssetOverviewTabs OperationCode = 517
	OperationCodeAssetOverviewTabContent OperationCode = 518
	OperationCodeAssetOverviewUnfreezeCache OperationCode = 519
	OperationCodeAssetOverviewSearch OperationCode = 520
	OperationCodeAssetOverviewSearchTabs OperationCode = 521
	OperationCodeAssetOverviewSearchTabContent OperationCode = 522
	OperationCodeAssetOverviewRecoverPlayerVault OperationCode = 523
	OperationCodeImmortalizeKillTrophy OperationCode = 524
	OperationCodeArmorySearch OperationCode = 525
	OperationCodeArmoryItemUsageStatistics OperationCode = 526
	OperationCodeArmoryActivityUsageStatistics OperationCode = 527
	OperationCodeHellDungeonUseStaticEntrance OperationCode = 528
	OperationCodeTravelIslandShowroom OperationCode = 529
	OperationCodeGetXuids OperationCode = 530
	OperationCodeXboxServiceTicket OperationCode = 531
	OperationCodeEvaluatePlatformPerks OperationCode = 532
	OperationCodeLinkAccountToXbox OperationCode = 533
	OperationCodeTravelFactionWarfarePortal OperationCode = 534
	OperationCodeRequestRedZoneEventStandings OperationCode = 535
	OperationCodeGetZergDebuffInfo OperationCode = 536
	OperationCodeRequestLoreSnippetStates OperationCode = 537
	OperationCodeRetrieveCarriableObjectStart OperationCode = 538
	OperationCodeRetrieveCarriableObjectCancel OperationCode = 539
	OperationCodeForfeitCustomMatch OperationCode = 540
	OperationCodeGetPartyMemberCluster OperationCode = 541
	OperationCodeSetPartyNavigation OperationCode = 542
	OperationCodeEndPartyNavigation OperationCode = 543
)

// OperationCodeNames maps a OperationCode to its upstream identifier.
var OperationCodeNames = map[OperationCode]string{
	OperationCodeUnused: "Unused",
	OperationCodePing: "Ping",
	OperationCodeJoin: "Join",
	OperationCodeVersionedOperation: "VersionedOperation",
	OperationCodeCreateAccount: "CreateAccount",
	OperationCodeLogin: "Login",
	OperationCodeCreateGuestAccount: "CreateGuestAccount",
	OperationCodeCreatePlatformOnlyAccount: "CreatePlatformOnlyAccount",
	OperationCodeSendCrashLog: "SendCrashLog",
	OperationCodeSendTraceRoute: "SendTraceRoute",
	OperationCodeSendVfxStats: "SendVfxStats",
	OperationCodeSendGamePingInfo: "SendGamePingInfo",
	OperationCodeCreateCharacter: "CreateCharacter",
	OperationCodeDeleteCharacter: "DeleteCharacter",
	OperationCodeSelectCharacter: "SelectCharacter",
	OperationCodeAcceptPopups: "AcceptPopups",
	OperationCodeRedeemKeycode: "RedeemKeycode",
	OperationCodeGetGameServerByCluster: "GetGameServerByCluster",
	OperationCodeGetShopPurchaseUrl: "GetShopPurchaseUrl",
	OperationCodeGetReferralSeasonDetails: "GetReferralSeasonDetails",
	OperationCodeGetReferralLink: "GetReferralLink",
	OperationCodeGetShopTilesForCategory: "GetShopTilesForCategory",
	OperationCodeMove: "Move",
	OperationCodeAttackStart: "AttackStart",
	OperationCodeCastStart: "CastStart",
	OperationCodeCastCancel: "CastCancel",
	OperationCodeTerminateToggleSpell: "TerminateToggleSpell",
	OperationCodeChannelingCancel: "ChannelingCancel",
	OperationCodeAttackBuildingStart: "AttackBuildingStart",
	OperationCodeInventoryDestroyItem: "InventoryDestroyItem",
	OperationCodeInventoryMoveItem: "InventoryMoveItem",
	OperationCodeInventoryRecoverItem: "InventoryRecoverItem",
	OperationCodeInventoryRecoverAllItems: "InventoryRecoverAllItems",
	OperationCodeInventorySplitStack: "InventorySplitStack",
	OperationCodeInventorySplitStackInto: "InventorySplitStackInto",
	OperationCodeInventoryStack: "InventoryStack",
	OperationCodeInventoryReorder: "InventoryReorder",
	OperationCodeInventoryDropAll: "InventoryDropAll",
	OperationCodeInventoryAddToStacks: "InventoryAddToStacks",
	OperationCodeInventoryMoveGivenItems: "InventoryMoveGivenItems",
	OperationCodeGetClusterData: "GetClusterData",
	OperationCodeChangeCluster: "ChangeCluster",
	OperationCodeConsoleCommand: "ConsoleCommand",
	OperationCodeChatMessage: "ChatMessage",
	OperationCodeReportClientError: "ReportClientError",
	OperationCodeRegisterToObject: "RegisterToObject",
	OperationCodeUnRegisterFromObject: "UnRegisterFromObject",
	OperationCodeCraftBuildingChangeSettings: "CraftBuildingChangeSettings",
	OperationCodeCraftBuildingTakeMoney: "CraftBuildingTakeMoney",
	OperationCodeRepairBuildingChangeSettings: "RepairBuildingChangeSettings",
	OperationCodeRepairBuildingTakeMoney: "RepairBuildingTakeMoney",
	OperationCodeActionBuildingChangeSettings: "ActionBuildingChangeSettings",
	OperationCodeHarvestStart: "HarvestStart",
	OperationCodeHarvestCancel: "HarvestCancel",
	OperationCodeTakeSilver: "TakeSilver",
	OperationCodeActionOnBuildingStart: "ActionOnBuildingStart",
	OperationCodeActionOnBuildingCancel: "ActionOnBuildingCancel",
	OperationCodeInstallResourceStart: "InstallResourceStart",
	OperationCodeInstallResourceCancel: "InstallResourceCancel",
	OperationCodeInstallSilver: "InstallSilver",
	OperationCodeBuildingFillNutrition: "BuildingFillNutrition",
	OperationCodeBuildingChangeRenovationState: "BuildingChangeRenovationState",
	OperationCodeBuildingBuySkin: "BuildingBuySkin",
	OperationCodeBuildingClaim: "BuildingClaim",
	OperationCodeBuildingGiveup: "BuildingGiveup",
	OperationCodeBuildingNutritionSilverStorageDeposit: "BuildingNutritionSilverStorageDeposit",
	OperationCodeBuildingNutritionSilverStorageWithdraw: "BuildingNutritionSilverStorageWithdraw",
	OperationCodeBuildingNutritionSilverRewardSet: "BuildingNutritionSilverRewardSet",
	OperationCodeConstructionSiteCreate: "ConstructionSiteCreate",
	OperationCodePlaceableObjectPlace: "PlaceableObjectPlace",
	OperationCodePlaceableObjectPlaceCancel: "PlaceableObjectPlaceCancel",
	OperationCodePlaceableObjectPickup: "PlaceableObjectPickup",
	OperationCodeFurnitureObjectUse: "FurnitureObjectUse",
	OperationCodeFarmableHarvest: "FarmableHarvest",
	OperationCodeFarmableFinishGrownItem: "FarmableFinishGrownItem",
	OperationCodeFarmableDestroy: "FarmableDestroy",
	OperationCodeFarmableGetProduct: "FarmableGetProduct",
	OperationCodeFarmableFill: "FarmableFill",
	OperationCodeTearDownConstructionSite: "TearDownConstructionSite",
	OperationCodeAuctionCreateOffer: "AuctionCreateOffer",
	OperationCodeAuctionCreateRequest: "AuctionCreateRequest",
	OperationCodeAuctionGetOffers: "AuctionGetOffers",
	OperationCodeAuctionGetRequests: "AuctionGetRequests",
	OperationCodeAuctionBuyOffer: "AuctionBuyOffer",
	OperationCodeAuctionAbortAuction: "AuctionAbortAuction",
	OperationCodeAuctionModifyAuction: "AuctionModifyAuction",
	OperationCodeAuctionAbortOffer: "AuctionAbortOffer",
	OperationCodeAuctionAbortRequest: "AuctionAbortRequest",
	OperationCodeAuctionSellRequest: "AuctionSellRequest",
	OperationCodeAuctionGetFinishedAuctions: "AuctionGetFinishedAuctions",
	OperationCodeAuctionGetFinishedAuctionsCount: "AuctionGetFinishedAuctionsCount",
	OperationCodeAuctionFetchAuction: "AuctionFetchAuction",
	OperationCodeAuctionGetMyOpenOffers: "AuctionGetMyOpenOffers",
	OperationCodeAuctionGetMyOpenRequests: "AuctionGetMyOpenRequests",
	OperationCodeAuctionGetMyOpenAuctions: "AuctionGetMyOpenAuctions",
	OperationCodeAuctionGetItemAverageStats: "AuctionGetItemAverageStats",
	OperationCodeAuctionGetItemAverageValue: "AuctionGetItemAverageValue",
	OperationCodeAuctionGetLowestOfferPrices: "AuctionGetLowestOfferPrices",
	OperationCodeContainerOpen: "ContainerOpen",
	OperationCodeContainerClose: "ContainerClose",
	OperationCodeContainerManageSubContainer: "ContainerManageSubContainer",
	OperationCodeRespawn: "Respawn",
	OperationCodeSuicide: "Suicide",
	OperationCodeJoinGuild: "JoinGuild",
	OperationCodeLeaveGuild: "LeaveGuild",
	OperationCodeCreateGuild: "CreateGuild",
	OperationCodeInviteToGuild: "InviteToGuild",
	OperationCodeDeclineGuildInvitation: "DeclineGuildInvitation",
	OperationCodeKickFromGuild: "KickFromGuild",
	OperationCodeInstantJoinGuild: "InstantJoinGuild",
	OperationCodeDuellingChallengePlayer: "DuellingChallengePlayer",
	OperationCodeDuellingAcceptChallenge: "DuellingAcceptChallenge",
	OperationCodeDuellingDenyChallenge: "DuellingDenyChallenge",
	OperationCodeChangeClusterTax: "ChangeClusterTax",
	OperationCodeClaimTerritory: "ClaimTerritory",
	OperationCodeGiveUpTerritory: "GiveUpTerritory",
	OperationCodeChangeTerritoryAccessRights: "ChangeTerritoryAccessRights",
	OperationCodeGetMonolithInfo: "GetMonolithInfo",
	OperationCodeGetClaimInfo: "GetClaimInfo",
	OperationCodeGetAttackInfo: "GetAttackInfo",
	OperationCodeGetTerritorySeasonPoints: "GetTerritorySeasonPoints",
	OperationCodeGetAttackSchedule: "GetAttackSchedule",
	OperationCodeGetMatches: "GetMatches",
	OperationCodeGetMatchDetails: "GetMatchDetails",
	OperationCodeJoinMatch: "JoinMatch",
	OperationCodeLeaveMatch: "LeaveMatch",
	OperationCodeGetClusterInstanceInfoForStaticCluster: "GetClusterInstanceInfoForStaticCluster",
	OperationCodeChangeChatSettings: "ChangeChatSettings",
	OperationCodeLogoutStart: "LogoutStart",
	OperationCodeLogoutCancel: "LogoutCancel",
	OperationCodeClaimOrbStart: "ClaimOrbStart",
	OperationCodeClaimOrbCancel: "ClaimOrbCancel",
	OperationCodeMatchLootChestOpeningStart: "MatchLootChestOpeningStart",
	OperationCodeMatchLootChestOpeningCancel: "MatchLootChestOpeningCancel",
	OperationCodeDepositToGuildAccount: "DepositToGuildAccount",
	OperationCodeWithdrawalFromAccount: "WithdrawalFromAccount",
	OperationCodeChangeGuildPayUpkeepFlag: "ChangeGuildPayUpkeepFlag",
	OperationCodeChangeGuildTax: "ChangeGuildTax",
	OperationCodeGetMyTerritories: "GetMyTerritories",
	OperationCodeMorganaCommand: "MorganaCommand",
	OperationCodeGetServerInfo: "GetServerInfo",
	OperationCodeSubscribeToCluster: "SubscribeToCluster",
	OperationCodeAnswerMercenaryInvitation: "AnswerMercenaryInvitation",
	OperationCodeGetCharacterEquipment: "GetCharacterEquipment",
	OperationCodeGetCharacterSteamAchievements: "GetCharacterSteamAchievements",
	OperationCodeGetCharacterStats: "GetCharacterStats",
	OperationCodeGetKillHistoryDetails: "GetKillHistoryDetails",
	OperationCodeReSpecAchievement: "ReSpecAchievement",
	OperationCodeChangeAvatar: "ChangeAvatar",
	OperationCodeGetRankings: "GetRankings",
	OperationCodeGetRank: "GetRank",
	OperationCodeGetGvgSeasonRankings: "GetGvgSeasonRankings",
	OperationCodeGetGvgSeasonRank: "GetGvgSeasonRank",
	OperationCodeGetGvgSeasonHistoryRankings: "GetGvgSeasonHistoryRankings",
	OperationCodeGetGvgSeasonGuildMemberHistory: "GetGvgSeasonGuildMemberHistory",
	OperationCodeKickFromGvGMatch: "KickFromGvGMatch",
	OperationCodeGetCrystalLeagueDailySeasonPoints: "GetCrystalLeagueDailySeasonPoints",
	OperationCodeGetChestLogs: "GetChestLogs",
	OperationCodeGetAccessRightLogs: "GetAccessRightLogs",
	OperationCodeGetGuildAccountLogs: "GetGuildAccountLogs",
	OperationCodeGetGuildAccountLogsLargeAmount: "GetGuildAccountLogsLargeAmount",
	OperationCodeInviteToPlayerTrade: "InviteToPlayerTrade",
	OperationCodePlayerTradeCancel: "PlayerTradeCancel",
	OperationCodePlayerTradeInvitationAccept: "PlayerTradeInvitationAccept",
	OperationCodePlayerTradeAddItem: "PlayerTradeAddItem",
	OperationCodePlayerTradeRemoveItem: "PlayerTradeRemoveItem",
	OperationCodePlayerTradeAcceptTrade: "PlayerTradeAcceptTrade",
	OperationCodePlayerTradeSetSilverOrGold: "PlayerTradeSetSilverOrGold",
	OperationCodeSendMiniMapPing: "SendMiniMapPing",
	OperationCodeStuck: "Stuck",
	OperationCodeBuyRealEstate: "BuyRealEstate",
	OperationCodeClaimRealEstate: "ClaimRealEstate",
	OperationCodeGiveUpRealEstate: "GiveUpRealEstate",
	OperationCodeChangeRealEstateOutline: "ChangeRealEstateOutline",
	OperationCodeGetMailInfos: "GetMailInfos",
	OperationCodeGetMailCount: "GetMailCount",
	OperationCodeReadMail: "ReadMail",
	OperationCodeSendNewMail: "SendNewMail",
	OperationCodeDeleteMail: "DeleteMail",
	OperationCodeMarkMailUnread: "MarkMailUnread",
	OperationCodeClaimAttachmentFromMail: "ClaimAttachmentFromMail",
	OperationCodeApplyToGuild: "ApplyToGuild",
	OperationCodeAnswerGuildApplication: "AnswerGuildApplication",
	OperationCodeRequestGuildFinderFilteredList: "RequestGuildFinderFilteredList",
	OperationCodeUpdateGuildRecruitmentInfo: "UpdateGuildRecruitmentInfo",
	OperationCodeRequestGuildRecruitmentInfo: "RequestGuildRecruitmentInfo",
	OperationCodeRequestGuildFinderNameSearch: "RequestGuildFinderNameSearch",
	OperationCodeRequestGuildFinderRecommendedList: "RequestGuildFinderRecommendedList",
	OperationCodeRegisterChatPeer: "RegisterChatPeer",
	OperationCodeSendChatMessage: "SendChatMessage",
	OperationCodeSendModeratorMessage: "SendModeratorMessage",
	OperationCodeJoinChatChannel: "JoinChatChannel",
	OperationCodeLeaveChatChannel: "LeaveChatChannel",
	OperationCodeSendWhisperMessage: "SendWhisperMessage",
	OperationCodeSay: "Say",
	OperationCodePlayEmote: "PlayEmote",
	OperationCodeStopEmote: "StopEmote",
	OperationCodeGetClusterMapInfo: "GetClusterMapInfo",
	OperationCodeAccessRightsChangeSettings: "AccessRightsChangeSettings",
	OperationCodeMount: "Mount",
	OperationCodeMountCancel: "MountCancel",
	OperationCodeBuyJourney: "BuyJourney",
	OperationCodeSetSaleStatusForEstate: "SetSaleStatusForEstate",
	OperationCodeResolveGuildOrPlayerName: "ResolveGuildOrPlayerName",
	OperationCodeGetRespawnInfos: "GetRespawnInfos",
	OperationCodeMakeHome: "MakeHome",
	OperationCodeLeaveHome: "LeaveHome",
	OperationCodeResurrectionReply: "ResurrectionReply",
	OperationCodeAllianceCreate: "AllianceCreate",
	OperationCodeAllianceDisband: "AllianceDisband",
	OperationCodeAllianceGetMemberInfos: "AllianceGetMemberInfos",
	OperationCodeAllianceInvite: "AllianceInvite",
	OperationCodeAllianceAnswerInvitation: "AllianceAnswerInvitation",
	OperationCodeAllianceCancelInvitation: "AllianceCancelInvitation",
	OperationCodeAllianceKickGuild: "AllianceKickGuild",
	OperationCodeAllianceLeave: "AllianceLeave",
	OperationCodeAllianceChangeGoldPaymentFlag: "AllianceChangeGoldPaymentFlag",
	OperationCodeAllianceGetDetailInfo: "AllianceGetDetailInfo",
	OperationCodeGetIslandInfos: "GetIslandInfos",
	OperationCodeBuyMyIsland: "BuyMyIsland",
	OperationCodeBuyGuildIsland: "BuyGuildIsland",
	OperationCodeUpgradeMyIsland: "UpgradeMyIsland",
	OperationCodeUpgradeGuildIsland: "UpgradeGuildIsland",
	OperationCodeTerritoryFillNutrition: "TerritoryFillNutrition",
	OperationCodeTeleportBack: "TeleportBack",
	OperationCodePartyInvitePlayer: "PartyInvitePlayer",
	OperationCodePartyRequestJoin: "PartyRequestJoin",
	OperationCodePartyAnswerInvitation: "PartyAnswerInvitation",
	OperationCodePartyAnswerJoinRequest: "PartyAnswerJoinRequest",
	OperationCodePartyLeave: "PartyLeave",
	OperationCodePartyKickPlayer: "PartyKickPlayer",
	OperationCodePartyMakeLeader: "PartyMakeLeader",
	OperationCodePartyChangeLootSetting: "PartyChangeLootSetting",
	OperationCodePartyMarkObject: "PartyMarkObject",
	OperationCodePartySetRole: "PartySetRole",
	OperationCodePartyChangeFactionWarfareRequestReinforcementsSetting: "PartyChangeFactionWarfareRequestReinforcementsSetting",
	OperationCodeSetGuildCodex: "SetGuildCodex",
	OperationCodeExitEnterStart: "ExitEnterStart",
	OperationCodeExitEnterCancel: "ExitEnterCancel",
	OperationCodeQuestGiverRequest: "QuestGiverRequest",
	OperationCodeGoldMarketGetBuyOffer: "GoldMarketGetBuyOffer",
	OperationCodeGoldMarketGetBuyOfferFromSilver: "GoldMarketGetBuyOfferFromSilver",
	OperationCodeGoldMarketGetSellOffer: "GoldMarketGetSellOffer",
	OperationCodeGoldMarketGetSellOfferFromSilver: "GoldMarketGetSellOfferFromSilver",
	OperationCodeGoldMarketBuyGold: "GoldMarketBuyGold",
	OperationCodeGoldMarketSellGold: "GoldMarketSellGold",
	OperationCodeGoldMarketCreateSellOrder: "GoldMarketCreateSellOrder",
	OperationCodeGoldMarketCreateBuyOrder: "GoldMarketCreateBuyOrder",
	OperationCodeGoldMarketGetInfos: "GoldMarketGetInfos",
	OperationCodeGoldMarketCancelOrder: "GoldMarketCancelOrder",
	OperationCodeGoldMarketGetAverageInfo: "GoldMarketGetAverageInfo",
	OperationCodeTreasureChestUsingStart: "TreasureChestUsingStart",
	OperationCodeTreasureChestUsingCancel: "TreasureChestUsingCancel",
	OperationCodeUseLootChest: "UseLootChest",
	OperationCodeUseShrine: "UseShrine",
	OperationCodeUseHellgateShrine: "UseHellgateShrine",
	OperationCodeGetSiegeBannerInfo: "GetSiegeBannerInfo",
	OperationCodeLaborerStartJob: "LaborerStartJob",
	OperationCodeLaborerTakeJobLoot: "LaborerTakeJobLoot",
	OperationCodeLaborerDismiss: "LaborerDismiss",
	OperationCodeLaborerMove: "LaborerMove",
	OperationCodeLaborerBuyItem: "LaborerBuyItem",
	OperationCodeLaborerUpgrade: "LaborerUpgrade",
	OperationCodeBuyPremium: "BuyPremium",
	OperationCodeRealEstateGetAuctionData: "RealEstateGetAuctionData",
	OperationCodeRealEstateBidOnAuction: "RealEstateBidOnAuction",
	OperationCodeFriendInvite: "FriendInvite",
	OperationCodeFriendAnswerInvitation: "FriendAnswerInvitation",
	OperationCodeFriendCancelnvitation: "FriendCancelnvitation",
	OperationCodeFriendRemove: "FriendRemove",
	OperationCodeEquipmentItemChangeSpell: "EquipmentItemChangeSpell",
	OperationCodeExpeditionRegister: "ExpeditionRegister",
	OperationCodeExpeditionRegisterCancel: "ExpeditionRegisterCancel",
	OperationCodeJoinExpedition: "JoinExpedition",
	OperationCodeDeclineExpeditionInvitation: "DeclineExpeditionInvitation",
	OperationCodeVoteStart: "VoteStart",
	OperationCodeVoteDoVote: "VoteDoVote",
	OperationCodeRatingDoRate: "RatingDoRate",
	OperationCodeEnteringExpeditionStart: "EnteringExpeditionStart",
	OperationCodeEnteringExpeditionCancel: "EnteringExpeditionCancel",
	OperationCodeActivateExpeditionCheckPoint: "ActivateExpeditionCheckPoint",
	OperationCodeArenaRegister: "ArenaRegister",
	OperationCodeArenaAddInvite: "ArenaAddInvite",
	OperationCodeArenaRegisterCancel: "ArenaRegisterCancel",
	OperationCodeArenaLeave: "ArenaLeave",
	OperationCodeJoinArenaMatch: "JoinArenaMatch",
	OperationCodeDeclineArenaInvitation: "DeclineArenaInvitation",
	OperationCodeEnteringArenaStart: "EnteringArenaStart",
	OperationCodeEnteringArenaCancel: "EnteringArenaCancel",
	OperationCodeArenaCustomMatch: "ArenaCustomMatch",
	OperationCodeUpdateCharacterStatement: "UpdateCharacterStatement",
	OperationCodeBoostFarmable: "BoostFarmable",
	OperationCodeGetStrikeHistory: "GetStrikeHistory",
	OperationCodeUseFunction: "UseFunction",
	OperationCodeUsePortalEntrance: "UsePortalEntrance",
	OperationCodeResetPortalBinding: "ResetPortalBinding",
	OperationCodeQueryPortalBinding: "QueryPortalBinding",
	OperationCodeClaimPaymentTransaction: "ClaimPaymentTransaction",
	OperationCodeChangeUseFlag: "ChangeUseFlag",
	OperationCodeClientPerformanceStats: "ClientPerformanceStats",
	OperationCodeExtendedHardwareStats: "ExtendedHardwareStats",
	OperationCodeClientLowMemoryWarning: "ClientLowMemoryWarning",
	OperationCodeTerritoryClaimStart: "TerritoryClaimStart",
	OperationCodeTerritoryClaimCancel: "TerritoryClaimCancel",
	OperationCodeDeliverCarriableObjectStart: "DeliverCarriableObjectStart",
	OperationCodeDeliverCarriableObjectCancel: "DeliverCarriableObjectCancel",
	OperationCodeTerritoryUpgradeWithPowerCrystal: "TerritoryUpgradeWithPowerCrystal",
	OperationCodeRequestAppStoreProducts: "RequestAppStoreProducts",
	OperationCodeVerifyProductPurchase: "VerifyProductPurchase",
	OperationCodeQueryGuildPlayerStats: "QueryGuildPlayerStats",
	OperationCodeQueryAllianceGuildStats: "QueryAllianceGuildStats",
	OperationCodeTrackAchievements: "TrackAchievements",
	OperationCodeSetAchievementsAutoLearn: "SetAchievementsAutoLearn",
	OperationCodeDepositItemToGuildCurrency: "DepositItemToGuildCurrency",
	OperationCodeWithdrawalItemFromGuildCurrency: "WithdrawalItemFromGuildCurrency",
	OperationCodeAuctionSellSpecificItemRequest: "AuctionSellSpecificItemRequest",
	OperationCodeFishingStart: "FishingStart",
	OperationCodeFishingCasting: "FishingCasting",
	OperationCodeFishingCast: "FishingCast",
	OperationCodeFishingCatch: "FishingCatch",
	OperationCodeFishingPull: "FishingPull",
	OperationCodeFishingGiveLine: "FishingGiveLine",
	OperationCodeFishingFinish: "FishingFinish",
	OperationCodeFishingCancel: "FishingCancel",
	OperationCodeCreateGuildAccessTag: "CreateGuildAccessTag",
	OperationCodeDeleteGuildAccessTag: "DeleteGuildAccessTag",
	OperationCodeRenameGuildAccessTag: "RenameGuildAccessTag",
	OperationCodeFlagGuildAccessTagGuildPermission: "FlagGuildAccessTagGuildPermission",
	OperationCodeAssignGuildAccessTag: "AssignGuildAccessTag",
	OperationCodeRemoveGuildAccessTagFromPlayer: "RemoveGuildAccessTagFromPlayer",
	OperationCodeModifyGuildAccessTagEditors: "ModifyGuildAccessTagEditors",
	OperationCodeRequestPublicAccessTags: "RequestPublicAccessTags",
	OperationCodeChangeAccessTagPublicFlag: "ChangeAccessTagPublicFlag",
	OperationCodeUpdateGuildAccessTag: "UpdateGuildAccessTag",
	OperationCodeSteamStartMicrotransaction: "SteamStartMicrotransaction",
	OperationCodeSteamFinishMicrotransaction: "SteamFinishMicrotransaction",
	OperationCodeRequestXboxPurchaseIntent: "RequestXboxPurchaseIntent",
	OperationCodeCloseXboxPurchaseIntent: "CloseXboxPurchaseIntent",
	OperationCodeSteamIdHasActiveAccount: "SteamIdHasActiveAccount",
	OperationCodeCheckEmailAccountState: "CheckEmailAccountState",
	OperationCodeLinkAccountToSteamId: "LinkAccountToSteamId",
	OperationCodeEpicIdHasActiveAccount: "EpicIdHasActiveAccount",
	OperationCodeLinkAccountToEpicId: "LinkAccountToEpicId",
	OperationCodeXboxIdHasActiveAccount: "XboxIdHasActiveAccount",
	OperationCodeInAppConfirmPaymentGooglePlay: "InAppConfirmPaymentGooglePlay",
	OperationCodeInAppConfirmPaymentAppleAppStore: "InAppConfirmPaymentAppleAppStore",
	OperationCodeInAppPurchaseRequest: "InAppPurchaseRequest",
	OperationCodeInAppPurchaseFailed: "InAppPurchaseFailed",
	OperationCodeCharacterSubscriptionInfo: "CharacterSubscriptionInfo",
	OperationCodeAccountSubscriptionInfo: "AccountSubscriptionInfo",
	OperationCodeBuyGvgSeasonBooster: "BuyGvgSeasonBooster",
	OperationCodeChangeFlaggingPrepare: "ChangeFlaggingPrepare",
	OperationCodeOverCharge: "OverCharge",
	OperationCodeOverChargeEnd: "OverChargeEnd",
	OperationCodeRequestTrusted: "RequestTrusted",
	OperationCodeChangeGuildLogo: "ChangeGuildLogo",
	OperationCodePartyFinderRegisterForUpdates: "PartyFinderRegisterForUpdates",
	OperationCodePartyFinderUnregisterForUpdates: "PartyFinderUnregisterForUpdates",
	OperationCodePartyFinderEnlistNewPartySearch: "PartyFinderEnlistNewPartySearch",
	OperationCodePartyFinderDeletePartySearch: "PartyFinderDeletePartySearch",
	OperationCodePartyFinderChangePartySearch: "PartyFinderChangePartySearch",
	OperationCodePartyFinderChangeRole: "PartyFinderChangeRole",
	OperationCodePartyFinderApplyForGroup: "PartyFinderApplyForGroup",
	OperationCodePartyFinderAcceptOrDeclineApplyForGroup: "PartyFinderAcceptOrDeclineApplyForGroup",
	OperationCodePartyFinderGetEquipmentSnapshot: "PartyFinderGetEquipmentSnapshot",
	OperationCodePartyFinderRegisterApplicants: "PartyFinderRegisterApplicants",
	OperationCodePartyFinderUnregisterApplicants: "PartyFinderUnregisterApplicants",
	OperationCodePartyFinderFulltextSearch: "PartyFinderFulltextSearch",
	OperationCodePartyFinderRequestEquipmentSnapshot: "PartyFinderRequestEquipmentSnapshot",
	OperationCodeGetPersonalSeasonTrackerData: "GetPersonalSeasonTrackerData",
	OperationCodeGetPersonalSeasonPastRewardData: "GetPersonalSeasonPastRewardData",
	OperationCodeUseConsumableFromInventory: "UseConsumableFromInventory",
	OperationCodeClaimPersonalSeasonReward: "ClaimPersonalSeasonReward",
	OperationCodeXignCodeMessageToServer: "XignCodeMessageToServer",
	OperationCodeBattlEyeMessageToServer: "BattlEyeMessageToServer",
	OperationCodeSetNextTutorialState: "SetNextTutorialState",
	OperationCodeAddPlayerToMuteList: "AddPlayerToMuteList",
	OperationCodeRemovePlayerFromMuteList: "RemovePlayerFromMuteList",
	OperationCodeProductShopUserEvent: "ProductShopUserEvent",
	OperationCodeGetVanityUnlocks: "GetVanityUnlocks",
	OperationCodeBuyVanityUnlocks: "BuyVanityUnlocks",
	OperationCodeGetMountSkins: "GetMountSkins",
	OperationCodeSetMountSkin: "SetMountSkin",
	OperationCodeSetWardrobe: "SetWardrobe",
	OperationCodeChangeCustomization: "ChangeCustomization",
	OperationCodeChangePlayerIslandData: "ChangePlayerIslandData",
	OperationCodeGetGuildChallengePoints: "GetGuildChallengePoints",
	OperationCodeSmartQueueJoin: "SmartQueueJoin",
	OperationCodeSmartQueueLeave: "SmartQueueLeave",
	OperationCodeSmartQueueSelectSpawnCluster: "SmartQueueSelectSpawnCluster",
	OperationCodeUpgradeHideout: "UpgradeHideout",
	OperationCodeInitHideoutAttackStart: "InitHideoutAttackStart",
	OperationCodeInitHideoutAttackCancel: "InitHideoutAttackCancel",
	OperationCodeHideoutFillNutrition: "HideoutFillNutrition",
	OperationCodeHideoutGetInfo: "HideoutGetInfo",
	OperationCodeHideoutGetOwnerInfo: "HideoutGetOwnerInfo",
	OperationCodeHideoutSetTribute: "HideoutSetTribute",
	OperationCodeHideoutUpgradeWithPowerCrystal: "HideoutUpgradeWithPowerCrystal",
	OperationCodeHideoutDeclareHQ: "HideoutDeclareHQ",
	OperationCodeHideoutUndeclareHQ: "HideoutUndeclareHQ",
	OperationCodeHideoutGetHQRequirements: "HideoutGetHQRequirements",
	OperationCodeHideoutBoost: "HideoutBoost",
	OperationCodeHideoutBoostConstruction: "HideoutBoostConstruction",
	OperationCodeOpenWorldAttackScheduleStart: "OpenWorldAttackScheduleStart",
	OperationCodeOpenWorldAttackScheduleCancel: "OpenWorldAttackScheduleCancel",
	OperationCodeOpenWorldAttackConquerStart: "OpenWorldAttackConquerStart",
	OperationCodeOpenWorldAttackConquerCancel: "OpenWorldAttackConquerCancel",
	OperationCodeGetOpenWorldAttackDetails: "GetOpenWorldAttackDetails",
	OperationCodeGetNextOpenWorldAttackScheduleTime: "GetNextOpenWorldAttackScheduleTime",
	OperationCodeRecoverVaultFromHideout: "RecoverVaultFromHideout",
	OperationCodeGetGuildEnergyDrainInfo: "GetGuildEnergyDrainInfo",
	OperationCodeChannelingUpdate: "ChannelingUpdate",
	OperationCodeUseCorruptedShrine: "UseCorruptedShrine",
	OperationCodeRequestEstimatedMarketValue: "RequestEstimatedMarketValue",
	OperationCodeLogFeedback: "LogFeedback",
	OperationCodeGetInfamyInfo: "GetInfamyInfo",
	OperationCodeGetPartySmartClusterQueuePriority: "GetPartySmartClusterQueuePriority",
	OperationCodeSetPartySmartClusterQueuePriority: "SetPartySmartClusterQueuePriority",
	OperationCodeClientAntiAutoClickerInfo: "ClientAntiAutoClickerInfo",
	OperationCodeClientBotPatternDetectionInfo: "ClientBotPatternDetectionInfo",
	OperationCodeClientAntiGatherClickerInfo: "ClientAntiGatherClickerInfo",
	OperationCodeLoadoutCreate: "LoadoutCreate",
	OperationCodeLoadoutRead: "LoadoutRead",
	OperationCodeLoadoutReadHeaders: "LoadoutReadHeaders",
	OperationCodeLoadoutUpdate: "LoadoutUpdate",
	OperationCodeLoadoutDelete: "LoadoutDelete",
	OperationCodeLoadoutOrderUpdate: "LoadoutOrderUpdate",
	OperationCodeLoadoutEquip: "LoadoutEquip",
	OperationCodeBatchUseItemCancel: "BatchUseItemCancel",
	OperationCodeEnlistFactionWarfare: "EnlistFactionWarfare",
	OperationCodeGetFactionWarfareWeeklyReport: "GetFactionWarfareWeeklyReport",
	OperationCodeClaimFactionWarfareWeeklyReport: "ClaimFactionWarfareWeeklyReport",
	OperationCodeGetFactionWarfareCampaignData: "GetFactionWarfareCampaignData",
	OperationCodeClaimFactionWarfareItemReward: "ClaimFactionWarfareItemReward",
	OperationCodeSendMemoryConsumption: "SendMemoryConsumption",
	OperationCodePickupCarriableObjectStart: "PickupCarriableObjectStart",
	OperationCodePickupCarriableObjectCancel: "PickupCarriableObjectCancel",
	OperationCodeSetSavingChestLogsFlag: "SetSavingChestLogsFlag",
	OperationCodeGetSavingChestLogsFlag: "GetSavingChestLogsFlag",
	OperationCodeRegisterGuestAccount: "RegisterGuestAccount",
	OperationCodeResendGuestAccountVerificationEmail: "ResendGuestAccountVerificationEmail",
	OperationCodeDoSimpleActionStart: "DoSimpleActionStart",
	OperationCodeDoSimpleActionCancel: "DoSimpleActionCancel",
	OperationCodeGetGvgSeasonContributionByActivity: "GetGvgSeasonContributionByActivity",
	OperationCodeGetGvgSeasonContributionByCrystalLeague: "GetGvgSeasonContributionByCrystalLeague",
	OperationCodeGetGuildMightCategoryContribution: "GetGuildMightCategoryContribution",
	OperationCodeGetGuildMightCategoryOverview: "GetGuildMightCategoryOverview",
	OperationCodeGetPvpChallengeData: "GetPvpChallengeData",
	OperationCodeClaimPvpChallengeWeeklyReward: "ClaimPvpChallengeWeeklyReward",
	OperationCodeGetPersonalMightStats: "GetPersonalMightStats",
	OperationCodeGetPvpChallengeSeasonRewards: "GetPvpChallengeSeasonRewards",
	OperationCodeGetPvpChallengeSeasonRewardItems: "GetPvpChallengeSeasonRewardItems",
	OperationCodeClaimPvpChallengeSeasonRewards: "ClaimPvpChallengeSeasonRewards",
	OperationCodeClaimPvpChallengeSeasonRewardItems: "ClaimPvpChallengeSeasonRewardItems",
	OperationCodeAuctionGetLoadoutOffers: "AuctionGetLoadoutOffers",
	OperationCodeAuctionBuyLoadoutOffer: "AuctionBuyLoadoutOffer",
	OperationCodeAccountDeletionRequest: "AccountDeletionRequest",
	OperationCodeAccountReactivationRequest: "AccountReactivationRequest",
	OperationCodeCreateModeratorNotesForAccount: "CreateModeratorNotesForAccount",
	OperationCodeGetModeratorNotesForAccount: "GetModeratorNotesForAccount",
	OperationCodeGetModerationEscalationDefiniton: "GetModerationEscalationDefiniton",
	OperationCodeEventBasedPopupAddSeen: "EventBasedPopupAddSeen",
	OperationCodeGetItemKillHistory: "GetItemKillHistory",
	OperationCodeGetVanityConsumables: "GetVanityConsumables",
	OperationCodeEquipKillEmote: "EquipKillEmote",
	OperationCodeChangeKillEmotePlayOnKnockdownSetting: "ChangeKillEmotePlayOnKnockdownSetting",
	OperationCodeBuyVanityConsumableCharges: "BuyVanityConsumableCharges",
	OperationCodeReclaimVanityItem: "ReclaimVanityItem",
	OperationCodeGetArenaRankings: "GetArenaRankings",
	OperationCodeGetCrystalLeagueStatistics: "GetCrystalLeagueStatistics",
	OperationCodeSendOptionsLog: "SendOptionsLog",
	OperationCodeSendControlsOptionsLog: "SendControlsOptionsLog",
	OperationCodeMistsUseImmediateReturnExit: "MistsUseImmediateReturnExit",
	OperationCodeMistsUseStaticEntrance: "MistsUseStaticEntrance",
	OperationCodeMistsUseCityRoadsEntrance: "MistsUseCityRoadsEntrance",
	OperationCodeChangeNewGuildMemberMail: "ChangeNewGuildMemberMail",
	OperationCodeGetNewGuildMemberMail: "GetNewGuildMemberMail",
	OperationCodeChangeGuildFactionAllegiance: "ChangeGuildFactionAllegiance",
	OperationCodeGetGuildFactionAllegiance: "GetGuildFactionAllegiance",
	OperationCodeGuildBannerChange: "GuildBannerChange",
	OperationCodeGuildGetOptionalStats: "GuildGetOptionalStats",
	OperationCodeGuildSetOptionalStats: "GuildSetOptionalStats",
	OperationCodeGetPlayerInfoForStalk: "GetPlayerInfoForStalk",
	OperationCodePayGoldForCharacterTypeChange: "PayGoldForCharacterTypeChange",
	OperationCodeQuickSellAuctionQueryAction: "QuickSellAuctionQueryAction",
	OperationCodeQuickSellAuctionSellAction: "QuickSellAuctionSellAction",
	OperationCodeFcmTokenToServer: "FcmTokenToServer",
	OperationCodeApnsTokenToServer: "ApnsTokenToServer",
	OperationCodeDeathRecap: "DeathRecap",
	OperationCodeAuctionFetchFinishedAuctions: "AuctionFetchFinishedAuctions",
	OperationCodeAbortAuctionFetchFinishedAuctions: "AbortAuctionFetchFinishedAuctions",
	OperationCodeRequestLegendaryEvenHistory: "RequestLegendaryEvenHistory",
	OperationCodePartyAnswerStartHuntRequest: "PartyAnswerStartHuntRequest",
	OperationCodeHuntAbort: "HuntAbort",
	OperationCodeUseFindTrackSpellFromItemPrepare: "UseFindTrackSpellFromItemPrepare",
	OperationCodeInteractWithTrackStart: "InteractWithTrackStart",
	OperationCodeInteractWithTrackCancel: "InteractWithTrackCancel",
	OperationCodeTerritoryRaidStart: "TerritoryRaidStart",
	OperationCodeTerritoryRaidCancel: "TerritoryRaidCancel",
	OperationCodeTerritoryClaimRaidedRawEnergyCrystalResult: "TerritoryClaimRaidedRawEnergyCrystalResult",
	OperationCodeGvGSeasonPlayerGuildParticipationDetails: "GvGSeasonPlayerGuildParticipationDetails",
	OperationCodeDailyMightBonus: "DailyMightBonus",
	OperationCodeClaimDailyMightBonus: "ClaimDailyMightBonus",
	OperationCodeGetFortificationGroupInfo: "GetFortificationGroupInfo",
	OperationCodeUpgradeFortificationGroup: "UpgradeFortificationGroup",
	OperationCodeCancelUpgradeFortificationGroup: "CancelUpgradeFortificationGroup",
	OperationCodeDowngradeFortificationGroup: "DowngradeFortificationGroup",
	OperationCodeGetClusterActivityChestEstimates: "GetClusterActivityChestEstimates",
	OperationCodePartyReadyCheckBegin: "PartyReadyCheckBegin",
	OperationCodePartyReadyCheckUpdate: "PartyReadyCheckUpdate",
	OperationCodeClaimAlbionJournalReward: "ClaimAlbionJournalReward",
	OperationCodeTrackAlbionJournalAchievements: "TrackAlbionJournalAchievements",
	OperationCodeTrackAlbionJournalAchievementSubCategory: "TrackAlbionJournalAchievementSubCategory",
	OperationCodeRequestOutlandsTeleportationUsage: "RequestOutlandsTeleportationUsage",
	OperationCodePickupFromPiledObjectStart: "PickupFromPiledObjectStart",
	OperationCodePickupFromPiledObjectCancel: "PickupFromPiledObjectCancel",
	OperationCodeAssetOverview: "AssetOverview",
	OperationCodeAssetOverviewTabs: "AssetOverviewTabs",
	OperationCodeAssetOverviewTabContent: "AssetOverviewTabContent",
	OperationCodeAssetOverviewUnfreezeCache: "AssetOverviewUnfreezeCache",
	OperationCodeAssetOverviewSearch: "AssetOverviewSearch",
	OperationCodeAssetOverviewSearchTabs: "AssetOverviewSearchTabs",
	OperationCodeAssetOverviewSearchTabContent: "AssetOverviewSearchTabContent",
	OperationCodeAssetOverviewRecoverPlayerVault: "AssetOverviewRecoverPlayerVault",
	OperationCodeImmortalizeKillTrophy: "ImmortalizeKillTrophy",
	OperationCodeArmorySearch: "ArmorySearch",
	OperationCodeArmoryItemUsageStatistics: "ArmoryItemUsageStatistics",
	OperationCodeArmoryActivityUsageStatistics: "ArmoryActivityUsageStatistics",
	OperationCodeHellDungeonUseStaticEntrance: "HellDungeonUseStaticEntrance",
	OperationCodeTravelIslandShowroom: "TravelIslandShowroom",
	OperationCodeGetXuids: "GetXuids",
	OperationCodeXboxServiceTicket: "XboxServiceTicket",
	OperationCodeEvaluatePlatformPerks: "EvaluatePlatformPerks",
	OperationCodeLinkAccountToXbox: "LinkAccountToXbox",
	OperationCodeTravelFactionWarfarePortal: "TravelFactionWarfarePortal",
	OperationCodeRequestRedZoneEventStandings: "RequestRedZoneEventStandings",
	OperationCodeGetZergDebuffInfo: "GetZergDebuffInfo",
	OperationCodeRequestLoreSnippetStates: "RequestLoreSnippetStates",
	OperationCodeRetrieveCarriableObjectStart: "RetrieveCarriableObjectStart",
	OperationCodeRetrieveCarriableObjectCancel: "RetrieveCarriableObjectCancel",
	OperationCodeForfeitCustomMatch: "ForfeitCustomMatch",
	OperationCodeGetPartyMemberCluster: "GetPartyMemberCluster",
	OperationCodeSetPartyNavigation: "SetPartyNavigation",
	OperationCodeEndPartyNavigation: "EndPartyNavigation",
}

// String returns the upstream identifier for the OperationCode.
func (c OperationCode) String() string {
	if n, ok := OperationCodeNames[c]; ok {
		return n
	}
	return "OperationCode(" + itoa(int(c)) + ")"
}
